/*
 * Auto-generated by tools/eml_export.py from:
 *   /Users/user/dev/research/eml/experiments/runs/d2_all/d2_all_run01_seed137_biased_20260507-142150.m
 * DO NOT EDIT BY HAND. Re-run the export tool after re-training.
 *
 * Symbolic interpretation (informational): y = e - log(exp(input_y) - log(input_x))   [paper §3 depth-2 target]
 *
 * Tree shape: depth=2, n_leaves=4, n_internal=3.
 *   leaves[i]      ∈ {0=1, 1=x, 2=y}
 *   gates_left[i]  ∈ {0=use child, 1=use constant 1}
 *   gates_right[i] ∈ {0=use child, 1=use constant 1}
 */

#ifndef MICROGPT_EML_TREE_EML_D2_RECOVERED_H
#define MICROGPT_EML_TREE_EML_D2_RECOVERED_H

#include "microgpt_eml.h"

static const unsigned char eml_d2_recovered_leaves[4] = { 0, 2, 2, 1 };
static const unsigned char eml_d2_recovered_gates_left[3] = { 1, 0, 1 };
static const unsigned char eml_d2_recovered_gates_right[3] = { 0, 0, 0 };

static const EmlTree eml_d2_recovered = {
  .depth = 2,
  .n_leaves = 4,
  .n_internal = 3,
  .leaves = eml_d2_recovered_leaves,
  .gates_left = eml_d2_recovered_gates_left,
  .gates_right = eml_d2_recovered_gates_right,
};

#endif /* MICROGPT_EML_TREE_EML_D2_RECOVERED_H */
