/*
 * MicroGPT-C — EML Organelle Demo
 * Copyright (c) 2026 Ajay Soni, Enjector Software Ltd.  MIT License.
 *
 * Demonstrates a "frozen organelle" recovered by the EML symbolic-regression
 * trainer (PyTorch, in the companion eml research repo) and deployed as a
 * compile-time constant in pure C99.
 *
 * The target relation is the paper's depth-2 EML expression:
 *     y = e - log( exp(input_y) - log(input_x) )           on (x, y) > 1
 *
 * Training (offline, in the companion eml research repo):
 *   - 200 noisy samples from this target with sigma = 0.1 Gaussian noise
 *   - Discrete-tree trainer at depth 2; 16/16 seeds recover the exact
 *     symbolic tree (snap MSE = noise variance, clean test MSE = 0)
 *   - The recovered tree is the literal target function above.
 *
 * Deployment (this demo):
 *   - The snapped tree is in c_eml_tree.h, generated by tools/eml_export.py
 *     from the trainer's discretized .m file.
 *   - Evaluation goes through src/microgpt_eml.{h,c}, which is ~150 lines
 *     of pure C99 + math.h.
 *
 * What this demo prints:
 *   1. In-domain noisy-train MSE  (should ~equal noise variance = 0.01)
 *   2. In-domain clean-test MSE   (should be 0 to machine precision)
 *   3. Extrapolation clean MSE    (should be 0 to machine precision)
 *   4. Quadratic-feature LinReg baseline on the same data, all three
 *      metrics, for context — see RESEARCH_EML_ORGANELLE.md for the
 *      full PySR/KAN comparison documented in the parent research.
 *
 * Why this matters for OPA:
 *   - This is an "interpretable exact" organelle: a deterministic C
 *     function with no floating-point parameter drift, no learning rate,
 *     no checkpoint to ship.  It's a single header literal.
 *   - When the underlying relation is a shallow elementary law observed
 *     under noise, this beats a neural organelle on out-of-distribution
 *     extrapolation by orders of magnitude (see RESEARCH_EML_ORGANELLE.md).
 *   - When it isn't (e.g. the OPA games), a neural organelle is required.
 *     The two organelle classes are complementary, not competitive.
 *
 * Build / run:
 *   cmake --build build --target eml_organelle_demo
 *   ./build/eml_organelle_demo
 */

#define _CRT_SECURE_NO_WARNINGS 1

#include "microgpt_eml.h"
#include "c_eml_tree.h"

#include <math.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>

/* ------------------------ Test target & data gen ------------------------ */

static scalar_t target_fn(scalar_t x, scalar_t y) {
  /* eml_d2: e - log(exp(y) - log(x)) — same as the trainer's depth-2 target. */
  return (scalar_t)(M_E - log(exp((double)y) - log((double)x)));
}

/*
 * Tiny Park-Miller minimal-standard LCG so we don't depend on platform-
 * specific RNG semantics for a reproducible demo.
 */
typedef struct { unsigned long s; } DemoRng;

static double demo_rng_uniform(DemoRng *r, double lo, double hi) {
  /* MINSTD: x_{n+1} = 48271 * x_n mod (2^31 - 1) */
  r->s = (r->s * 48271UL) % 2147483647UL;
  double u = (double)r->s / 2147483647.0;
  return lo + (hi - lo) * u;
}

/*
 * Box-Muller for Gaussian samples; scratch state shared with the LCG.
 */
static double demo_rng_normal(DemoRng *r, double mean, double sigma) {
  double u1 = demo_rng_uniform(r, 1e-12, 1.0);
  double u2 = demo_rng_uniform(r, 0.0, 1.0);
  double z = sqrt(-2.0 * log(u1)) * cos(2.0 * M_PI * u2);
  return mean + sigma * z;
}

/* ----------------------------- Linear-regression baseline ------------- */
/*
 * Closed-form OLS on quadratic features (1, x, y, x*y, x^2, y^2) for the
 * (x, y, target) data we sample.  This matches the LinReg baseline used
 * in the parent research's §9.3.2 / §9.3.3 tables.
 *
 * We fit via normal equations using a tiny 6x6 Gauss-Jordan inverse.
 * For 200 training points this is fine.
 */

#define NFEAT 6

static void build_features(scalar_t x, scalar_t y, double *out) {
  out[0] = 1.0;
  out[1] = (double)x;
  out[2] = (double)y;
  out[3] = (double)x * (double)y;
  out[4] = (double)x * (double)x;
  out[5] = (double)y * (double)y;
}

/* Solve A * w = b where A is NFEAT x NFEAT (row-major). w overwrites b. */
static int solve_6x6(double A[NFEAT][NFEAT], double b[NFEAT]) {
  for (int i = 0; i < NFEAT; ++i) {
    /* partial pivot */
    int piv = i;
    double maxv = fabs(A[i][i]);
    for (int r = i + 1; r < NFEAT; ++r) {
      if (fabs(A[r][i]) > maxv) { piv = r; maxv = fabs(A[r][i]); }
    }
    if (maxv < 1e-12) return 0; /* singular */
    if (piv != i) {
      for (int c = 0; c < NFEAT; ++c) {
        double t = A[i][c]; A[i][c] = A[piv][c]; A[piv][c] = t;
      }
      double t = b[i]; b[i] = b[piv]; b[piv] = t;
    }
    /* eliminate */
    for (int r = 0; r < NFEAT; ++r) {
      if (r == i) continue;
      double f = A[r][i] / A[i][i];
      if (fabs(f) < 1e-15) continue;
      for (int c = i; c < NFEAT; ++c) A[r][c] -= f * A[i][c];
      b[r] -= f * b[i];
    }
  }
  for (int i = 0; i < NFEAT; ++i) b[i] /= A[i][i];
  return 1;
}

static void fit_linreg(const scalar_t *xs, const scalar_t *ys,
                       const scalar_t *targets, size_t n, double w[NFEAT]) {
  double A[NFEAT][NFEAT] = {{0}};
  double b[NFEAT] = {0};
  double feat[NFEAT];
  for (size_t i = 0; i < n; ++i) {
    build_features(xs[i], ys[i], feat);
    for (int r = 0; r < NFEAT; ++r) {
      for (int c = 0; c < NFEAT; ++c) A[r][c] += feat[r] * feat[c];
      b[r] += feat[r] * (double)targets[i];
    }
  }
  if (!solve_6x6(A, b)) {
    for (int i = 0; i < NFEAT; ++i) w[i] = 0.0;
    return;
  }
  for (int i = 0; i < NFEAT; ++i) w[i] = b[i];
}

static double linreg_predict(const double w[NFEAT], scalar_t x, scalar_t y) {
  double feat[NFEAT];
  build_features(x, y, feat);
  double acc = 0.0;
  for (int i = 0; i < NFEAT; ++i) acc += w[i] * feat[i];
  return acc;
}

static double linreg_mse(const double w[NFEAT], const scalar_t *xs,
                         const scalar_t *ys, const scalar_t *targets, size_t n) {
  double acc = 0.0;
  for (size_t i = 0; i < n; ++i) {
    double d = linreg_predict(w, xs[i], ys[i]) - (double)targets[i];
    acc += d * d;
  }
  return n ? acc / (double)n : 0.0;
}

static double linreg_max_err(const double w[NFEAT], const scalar_t *xs,
                             const scalar_t *ys, const scalar_t *targets, size_t n) {
  double worst = 0.0;
  for (size_t i = 0; i < n; ++i) {
    double d = fabs(linreg_predict(w, xs[i], ys[i]) - (double)targets[i]);
    if (d > worst) worst = d;
  }
  return worst;
}

/* ----------------------------- Test runner ---------------------------- */

static void make_data(DemoRng *rng, double lo, double hi, double sigma,
                      size_t n, scalar_t *xs, scalar_t *ys,
                      scalar_t *targets_clean, scalar_t *targets_noisy) {
  for (size_t i = 0; i < n; ++i) {
    xs[i] = (scalar_t)demo_rng_uniform(rng, lo, hi);
    ys[i] = (scalar_t)demo_rng_uniform(rng, lo, hi);
    scalar_t t = target_fn(xs[i], ys[i]);
    targets_clean[i] = t;
    if (targets_noisy) {
      targets_noisy[i] = (scalar_t)((double)t + demo_rng_normal(rng, 0.0, sigma));
    }
  }
}

int main(void) {
  enum { N_TRAIN = 200, N_TEST = 1000, N_EXTRAP = 1000 };
  static scalar_t xs_tr[N_TRAIN], ys_tr[N_TRAIN];
  static scalar_t targets_clean_tr[N_TRAIN], targets_noisy_tr[N_TRAIN];
  static scalar_t xs_te[N_TEST], ys_te[N_TEST];
  static scalar_t targets_clean_te[N_TEST];
  static scalar_t xs_ex[N_EXTRAP], ys_ex[N_EXTRAP];
  static scalar_t targets_clean_ex[N_EXTRAP];

  /* Reproducibility: pin the RNG seeds so this run prints the same numbers
   * whenever the demo is re-run (matches the trainer's 2026 data seed).
   */
  DemoRng rng_tr = { .s = 2026 };
  DemoRng rng_te = { .s = 2027 };
  DemoRng rng_ex = { .s = 2028 };

  const double sigma = 0.1;
  make_data(&rng_tr, 1.0, 3.0, sigma, N_TRAIN,
            xs_tr, ys_tr, targets_clean_tr, targets_noisy_tr);
  make_data(&rng_te, 1.0, 3.0, 0.0, N_TEST,
            xs_te, ys_te, targets_clean_te, NULL);
  make_data(&rng_ex, 0.5, 5.0, 0.0, N_EXTRAP,
            xs_ex, ys_ex, targets_clean_ex, NULL);

  /* ---------- EML organelle (frozen, snapped tree from header) ---------- */
  scalar_t eml_train_mse = eml_mse(&eml_d2_recovered, xs_tr, ys_tr,
                                   targets_noisy_tr, N_TRAIN);
  scalar_t eml_test_mse = eml_mse(&eml_d2_recovered, xs_te, ys_te,
                                  targets_clean_te, N_TEST);
  scalar_t eml_test_max = eml_max_abs_err(&eml_d2_recovered, xs_te, ys_te,
                                          targets_clean_te, N_TEST);
  scalar_t eml_extrap_mse = eml_mse(&eml_d2_recovered, xs_ex, ys_ex,
                                    targets_clean_ex, N_EXTRAP);
  scalar_t eml_extrap_max = eml_max_abs_err(&eml_d2_recovered, xs_ex, ys_ex,
                                            targets_clean_ex, N_EXTRAP);

  /* ---------- LinReg baseline (quadratic features, OLS in C) ---------- */
  double w[NFEAT];
  fit_linreg(xs_tr, ys_tr, targets_noisy_tr, N_TRAIN, w);
  double lin_train_mse = linreg_mse(w, xs_tr, ys_tr, targets_noisy_tr, N_TRAIN);
  double lin_test_mse = linreg_mse(w, xs_te, ys_te, targets_clean_te, N_TEST);
  double lin_test_max = linreg_max_err(w, xs_te, ys_te, targets_clean_te, N_TEST);
  double lin_extrap_mse = linreg_mse(w, xs_ex, ys_ex, targets_clean_ex, N_EXTRAP);
  double lin_extrap_max = linreg_max_err(w, xs_ex, ys_ex, targets_clean_ex, N_EXTRAP);

  /* ---------- Report ---------- */
  printf("MicroGPT-C  EML Organelle Demo\n");
  printf("  Target: y = e - log(exp(input_y) - log(input_x))\n");
  printf("  Train: %d points on [1, 3]^2, sigma=%.2f Gaussian noise\n",
         (int)N_TRAIN, sigma);
  printf("  In-domain test: %d clean points on [1, 3]^2\n", (int)N_TEST);
  printf("  Extrapolation: %d clean points on [0.5, 5.0]^2 (outside training)\n",
         (int)N_EXTRAP);
  printf("\n");
  printf("                       train MSE   test MSE   test max|err|"
         "   extrap MSE   extrap max|err|\n");
  printf("  ---------------------------------------------------------"
         "---------------------------\n");
  printf("  EML organelle      %10.3e %10.3e   %10.3e   %10.3e   %10.3e\n",
         (double)eml_train_mse, (double)eml_test_mse, (double)eml_test_max,
         (double)eml_extrap_mse, (double)eml_extrap_max);
  printf("  LinReg (quadratic) %10.3e %10.3e   %10.3e   %10.3e   %10.3e\n",
         lin_train_mse, lin_test_mse, lin_test_max,
         lin_extrap_mse, lin_extrap_max);
  printf("\n");
  printf("Notes\n");
  printf("  - EML train MSE should be ~sigma^2 = %.4f (the optimal residual\n",
         sigma * sigma);
  printf("    for any *correct* model on noisy data).\n");
  printf("  - EML test/extrap MSE should be 0 to machine precision because\n");
  printf("    the snapped tree IS the target function exactly.\n");
  printf("  - LinReg in-domain MSE is small because the target is smooth\n");
  printf("    and quadratic features approximate well, but extrapolation\n");
  printf("    error is orders of magnitude larger.\n");
  printf("\n");
  printf("Tree shape: depth=%d, %d leaves, %d internal nodes (snapped, no\n",
         eml_d2_recovered.depth, eml_d2_recovered.n_leaves,
         eml_d2_recovered.n_internal);
  printf("            floating-point parameters; deterministic).\n");
  return 0;
}
