/*
 * MicroGPT-C — Wiring Organelle Demo (Pipeline IR Phase 3c → 4)
 *
 * Trains a small word-level Transformer on the templated Pipeline IR
 * corpus generated by tools/pipeline_corpus_gen, then evaluates novel-
 * prompt generation: given a held-out comment line, can the model
 * produce a graph that (a) parses, (b) verifies strictly, and now in
 * Phase 4 (c) uses the right *real* primitives from the w_vm_functions
 * vocabulary (bmi, compound, sigmoid, gcd, apply_tax, …)?
 *
 * Pipeline:
 *   1. Read the standard `pipeline_corpus_train.txt` and
 *      `pipeline_corpus_val.txt` files (produced by pipeline_corpus_gen
 *      train.txt val.txt).
 *   2. Convert each multi-line example to a single-line form by
 *      replacing internal '\n' with ' __NL__ '. Insert a blank line
 *      between examples for opa_load_docs_multiline.
 *   3. Train via organelle_train_words().
 *   4. For each val prompt: feed prompt + __NL__ token, sample word
 *      tokens until we emit `@end`. Reconstruct the graph text by
 *      replacing __NL__ with newline.
 *   5. Try pipeline_parse_text → pipeline_verify on each generated
 *      graph. Phase 3 reports parse-rate / verify-rate / samples.
 *   6. PHASE 4: separately load `pipeline_corpus_held_out.txt`
 *      (annotated natural-English prompts NOT in train/val) and
 *      report strict-verify rate + primitive-fidelity rate as the
 *      headline metric for true tool composition.
 *
 * Architecture: 4-layer 96-emb 384-block, 5000 train steps (Phase 4
 * scale-up from Phase 3g's 2-layer 48-emb / 2000 steps to handle a
 * 60+-primitive vocabulary and 272-example corpus). The V4 active-
 * attention stack (PARTIAL_ROPE/ATTN_SINK/QK_NORM) is NOT enabled —
 * prior codegen ablation showed -30pp regression on grammar-rigid
 * generation, and this is grammar-rigid by definition.
 *
 * Headline (Phase 4): 65% strict-verify, 35% primitive-fidelity on
 * 20 natural-English held-out prompts. See RESEARCH_PIPELINE_IR.md §17.
 *
 * Phase 5b: post-parse pipeline_repair() drops internally-inconsistent
 * nodes/edges and unused sig ports, recovering verifiable subgraphs
 * from partially-broken organelle outputs. **Headline lift: 65% → 75%
 * strict-verify (+10pp) — see RESEARCH_PIPELINE_IR.md §19.**
 *
 * Phase 6: end-to-end execution via wiring_natives_dispatch() — 40
 * C-implemented primitives (add, multiply, sigmoid, compound, bmi, gcd,
 * factorial, fibonacci, …) plug into pipeline_execute(). Verified
 * graphs run on test inputs and produce numeric answers.
 * **Headline: 40% (8/20) prompt → graph → numeric answer; 6/8
 * arithmetically correct — see RESEARCH_PIPELINE_IR.md §20.**
 *
 * Phase 7: reference-answer correctness suite — wiring_references.{h,c}
 * computes the canonical expected answer per held-out prompt; the demo
 * compares exec_result == reference and reports `match` or `drift`.
 * **Headline: 35% (7/20) numerically correct end-to-end; 87.5%
 * accuracy among executing graphs — see RESEARCH_PIPELINE_IR.md §21.**
 *
 * Phase 8: multi-input correctness + self-consistency vote re-ranking.
 * Each held-out prompt is tested against 5 distinct input sets; a
 * candidate is "correct" iff its 5-vector matches the reference's
 * 5-vector exactly. The demo collects every verified candidate's
 * 5-vector during voting, then picks the self-consistent majority
 * winner. **Headline: 40% (8/20) correct on all 5 inputs (corrected
 * baseline after the Phase 10 reference fix); bimodal pattern shows
 * model is either right on all 5 or wrong on all 5. See
 * RESEARCH_PIPELINE_IR.md §22.**
 *
 * Phase 9: capacity scaling 540K → 1.49M params. NEGATIVE RESULT —
 * regressed to 35% (verify rate dropped 75% → 60%) due to over-fit on
 * 281-example corpus. Architecture reverted. See §23.
 *
 * Phase 10: argument-order paraphrases (10 new examples disambiguating
 * percentage, apply_tax, compound argument orders). HELD THE LINE at
 * 35% — the corrected reference (which now accepts the model's plural-
 * "expenses" reading of #13) lifts Phase 8 retrospectively to 40%, but
 * Phase 10 with the same fix is also 35%. Arg-order signal worked at
 * the fidelity level (#13 fidelity: N → Y) without changing the headline.
 * See §24.
 *
 * Copyright (c) 2026 Ajay Soni, Enjector Software Ltd. MIT License.
 */

#define _CRT_SECURE_NO_WARNINGS 1

#include "microgpt.h"
#include "microgpt_organelle.h"
#include "microgpt_pipeline.h"
#include "microgpt_vr.h"
#include "wiring_anchor_graphs.h"
#include "wiring_geo_classifier.h"
#include "wiring_natives.h"
#include "wiring_references.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef NUM_STEPS
#define NUM_STEPS 5000
#endif

#define INLINE_TRAIN_PATH "wiring_corpus_inline_train.txt"
#define INLINE_VAL_PATH   "wiring_corpus_inline_val.txt"
#define CKPT_PATH         "wiring_organelle.ckpt"

/* Phase 15 — planner organelle paths. */
#define PLANNER_CORPUS_RAW    "pipeline_corpus_planner.txt"
#define PLANNER_INLINE_PATH   "planner_corpus_inline.txt"
#define PLANNER_CKPT_PATH     "wiring_planner.ckpt"

/* Phase 17 — multi-seed wiring ensemble.
 * 3 wiring organelles with different srand seeds; 16 votes distributed
 * round-robin across them so the candidate pool draws from 3 distinct
 * models. Contracts variance and captures the union of correct prompts
 * across seeds. */
#define ENSEMBLE_SIZE 3
static const char *ENSEMBLE_CKPTS[ENSEMBLE_SIZE] = {
    "wiring_organelle.ckpt",
    "wiring_organelle_2.ckpt",
    "wiring_organelle_3.ckpt",
};
static const int ENSEMBLE_SEEDS[ENSEMBLE_SIZE] = { 42, 43, 44 };
static const char *ENSEMBLE_NAMES[ENSEMBLE_SIZE] = {
    "wiring_organelle",
    "wiring_organelle_2",
    "wiring_organelle_3",
};

/* ============================================================
 *  Corpus preprocessing — inline each example on one line.
 *  Replaces '\n' with ' __NL__ ' inside each example and writes
 *  examples separated by blank lines so opa_load_docs_multiline
 *  treats each as its own doc.
 * ============================================================ */
static int preprocess_corpus(const char *src_path, const char *dst_path,
                             int *n_examples_out, char ***val_prompts_out) {
    FILE *fin = fopen(src_path, "r");
    if (!fin) { fprintf(stderr, "preprocess: cannot open %s\n", src_path); return -1; }
    FILE *fout = fopen(dst_path, "w");
    if (!fout) { fclose(fin); fprintf(stderr, "preprocess: cannot write %s\n", dst_path); return -1; }

    char **prompts = NULL;
    int n_prompts = 0;
    int n_prompts_cap = 0;

    char line[2048];
    /* State machine. We accumulate one example at a time into `buf`,
     * triggered by a `// ` comment line at the start. The example ends
     * when we encounter `---` on its own line. */
    char *buf = NULL;
    size_t buf_cap = 0;
    size_t buf_len = 0;
    int in_example = 0;
    char current_prompt[1024] = "";

    while (fgets(line, sizeof(line), fin)) {
        /* Strip trailing newline. */
        size_t l = strlen(line);
        while (l > 0 && (line[l-1] == '\n' || line[l-1] == '\r')) line[--l] = '\0';

        /* Skip comment lines that start with `# ` (corpus header). */
        if (line[0] == '#') continue;

        if (!in_example) {
            /* Looking for a `// prompt` start-of-example. */
            if (line[0] == '/' && line[1] == '/') {
                strncpy(current_prompt, line, sizeof(current_prompt) - 1);
                current_prompt[sizeof(current_prompt) - 1] = '\0';
                in_example = 1;
                buf_len = 0;
                /* Append the prompt + __NL__ to the buf. */
                size_t add = strlen(line) + strlen(" __NL__ ") + 1;
                if (buf_len + add >= buf_cap) {
                    buf_cap = buf_cap ? buf_cap * 2 : 4096;
                    while (buf_cap < buf_len + add) buf_cap *= 2;
                    buf = (char *)realloc(buf, buf_cap);
                }
                buf_len += (size_t)snprintf(buf + buf_len, buf_cap - buf_len,
                                            "%s __NL__ ", line);
            }
            /* Otherwise skip blank/junk between examples. */
            continue;
        }

        /* Inside an example. End of example marker = `---`. */
        if (strcmp(line, "---") == 0) {
            /* Write inline example to output. */
            fprintf(fout, "%s\n\n", buf);
            /* Capture prompt for held-out evaluation. */
            if (n_prompts == n_prompts_cap) {
                n_prompts_cap = n_prompts_cap ? n_prompts_cap * 2 : 16;
                prompts = (char **)realloc(prompts, sizeof(char *) * (size_t)n_prompts_cap);
            }
            prompts[n_prompts++] = strdup(current_prompt);
            in_example = 0;
            buf_len = 0;
            continue;
        }

        /* Append `line __NL__ ` to buf. */
        size_t add = strlen(line) + strlen(" __NL__ ") + 1;
        if (buf_len + add >= buf_cap) {
            buf_cap = buf_cap ? buf_cap * 2 : 4096;
            while (buf_cap < buf_len + add) buf_cap *= 2;
            buf = (char *)realloc(buf, buf_cap);
        }
        buf_len += (size_t)snprintf(buf + buf_len, buf_cap - buf_len,
                                    "%s __NL__ ", line);
    }

    free(buf);
    fclose(fin);
    fclose(fout);
    *n_examples_out = n_prompts;
    *val_prompts_out = prompts;
    return 0;
}

/* ============================================================
 *  Phase 15 — Planner corpus preprocessing.
 *
 *  Planner training data has format:
 *      // <prompt>
 *      FAMILY: <family_name>
 *      ---
 *
 *  We inline each pair as a single training line:
 *      "// <prompt> __NL__ FAMILY: <family_name> __NL__"
 *  so the word-level tokenizer treats it as one document.
 *  At inference, the planner is fed "<prompt> __NL__ FAMILY:" and
 *  greedy-sampled until __NL__ — the predicted family is the words in
 *  between.
 * ============================================================ */
static int preprocess_planner_corpus(const char *src_path, const char *dst_path) {
    FILE *fin = fopen(src_path, "r");
    if (!fin) { fprintf(stderr, "preprocess_planner: cannot open %s\n", src_path); return -1; }
    FILE *fout = fopen(dst_path, "w");
    if (!fout) { fclose(fin); fprintf(stderr, "preprocess_planner: cannot write %s\n", dst_path); return -1; }

    char line[2048];
    char prompt[1024] = "";
    char family[256]  = "";
    int  in_example = 0;
    int  n = 0;

    while (fgets(line, sizeof(line), fin)) {
        size_t l = strlen(line);
        while (l > 0 && (line[l-1] == '\n' || line[l-1] == '\r')) line[--l] = '\0';
        if (line[0] == '#') continue;
        if (!in_example) {
            if (line[0] == '/' && line[1] == '/') {
                strncpy(prompt, line, sizeof(prompt) - 1);
                prompt[sizeof(prompt) - 1] = '\0';
                in_example = 1;
                family[0] = '\0';
            }
            continue;
        }
        if (strncmp(line, "FAMILY:", 7) == 0) {
            const char *p = line + 7;
            while (*p == ' ' || *p == '\t') p++;
            strncpy(family, p, sizeof(family) - 1);
            family[sizeof(family) - 1] = '\0';
            continue;
        }
        if (strcmp(line, "---") == 0) {
            if (prompt[0] && family[0]) {
                fprintf(fout, "%s __NL__ FAMILY: %s __NL__\n\n", prompt, family);
                n++;
            }
            in_example = 0;
            prompt[0] = '\0';
            family[0] = '\0';
            continue;
        }
    }
    fclose(fin);
    fclose(fout);
    fprintf(stderr, "planner: preprocessed %d (prompt, family) pairs\n", n);
    return n;
}

/* Phase 15 — predict the template family for an arbitrary prompt by
 * feeding "<prompt> __NL__ FAMILY:" to the planner organelle and
 * greedy-decoding until __NL__. Writes the predicted family (without
 * the "FAMILY:" prefix) to out. Returns out length, or 0 on failure. */
static int planner_predict_family(const Organelle *planner, const MicrogptConfig *cfg,
                                  const char *prompt, char *out, int max_out_bytes) {
    if (max_out_bytes <= 0) return 0;
    out[0] = '\0';
    const WordVocab *wv = &planner->word_vocab;
    int nl = cfg->n_layer;

    scalar_t **keys = (scalar_t **)malloc((size_t)nl * sizeof(scalar_t *));
    scalar_t **values = (scalar_t **)malloc((size_t)nl * sizeof(scalar_t *));
    size_t *cache_len = (size_t *)calloc((size_t)nl, sizeof(size_t));
    for (int l = 0; l < nl; l++) {
        keys[l]   = kv_cache_alloc(cfg);
        values[l] = kv_cache_alloc(cfg);
    }
    scalar_t *logits = (scalar_t *)malloc(wv->vocab_size * sizeof(scalar_t));
    int pos = 0;

    forward_inference(planner->model, wv->bos_id, pos, keys, values, cache_len, logits);
    pos++;

    /* Build prompt + " __NL__ FAMILY:" — the conditioning context. */
    char ctx[2048];
    snprintf(ctx, sizeof(ctx), "%s __NL__ FAMILY:", prompt);
    size_t *ids = (size_t *)malloc((size_t)cfg->block_size * sizeof(size_t));
    size_t n_in = tokenize_words(ctx, strlen(ctx), wv, ids, (size_t)cfg->block_size);
    for (size_t i = 0; i < n_in && pos < cfg->block_size - 1; i++) {
        forward_inference(planner->model, ids[i], pos, keys, values, cache_len, logits);
        pos++;
    }
    free(ids);

    /* Look up __NL__ token id. */
    size_t nl_token_id = wv->unk_id;
    for (size_t i = 0; i < wv->vocab_size; i++) {
        if (wv->words[i] && strcmp(wv->words[i], "__NL__") == 0) {
            nl_token_id = i;
            break;
        }
    }

    /* Greedy decode (low temperature) up to ~6 words until __NL__. */
    int out_pos = 0;
    for (int g = 0; g < 6 && pos < cfg->block_size - 1; g++) {
        size_t token = sample_token(logits, wv->vocab_size, (scalar_t)0.10f);
        if (token == nl_token_id) break;
        if (token == wv->bos_id) break;
        const char *word = (token < wv->vocab_size && wv->words[token])
                              ? wv->words[token] : "";
        if (!word[0]) break;
        if (out_pos > 0 && out_pos < max_out_bytes - 1) out[out_pos++] = '_';
        size_t wlen = strlen(word);
        for (size_t c = 0; c < wlen && out_pos < max_out_bytes - 1; c++) {
            out[out_pos++] = word[c];
        }
        out[out_pos] = '\0';
        forward_inference(planner->model, token, pos, keys, values, cache_len, logits);
        pos++;
    }

    free(logits);
    for (int l = 0; l < nl; l++) {
        kv_cache_free(keys[l]);
        kv_cache_free(values[l]);
    }
    free(keys); free(values); free(cache_len);
    return out_pos;
}

/* Returns a score for how well `family` (planner output) matches
 * `graph_name` (candidate's @graph name).
 *   - 2 if family == graph_name exactly (or after stripping tpl_/seed_)
 *   - 1 if family is a prefix of graph_name (the family-level case)
 *   - 0 otherwise.
 *
 * Phase 15b: Phase 15a emitted family-only ("tpl_fib_fact_op") so all
 * 16 op-variants matched equally — re-ranking was a no-op within a
 * family. Phase 15b's planner emits full graph names ("fib_fact_op_add")
 * which exact-match a single candidate. The graded score lets us prefer
 * exact matches over prefix matches when both exist. */
static int family_matches_graph_name(const char *family, const char *graph_name) {
    if (!family || !graph_name) return 0;
    const char *fam = family;
    if (strncmp(fam, "tpl_", 4) == 0) fam += 4;
    else if (strncmp(fam, "seed_", 5) == 0) fam += 5;
    if (strcmp(fam, graph_name) == 0) return 2;  /* exact */
    size_t fl = strlen(fam);
    return (strncmp(graph_name, fam, fl) == 0) ? 1 : 0;  /* prefix */
}

/* Extract the @graph name from a generated text. Returns 1 on success
 * with name written to out (caller buffer ≥64 bytes), 0 otherwise. */
static int extract_graph_name(const char *txt, char *out, int max_out) {
    if (!txt || !out || max_out <= 0) return 0;
    out[0] = '\0';
    const char *p = strstr(txt, "@graph");
    if (!p) return 0;
    p += 6;
    while (*p == ' ' || *p == '\t') p++;
    int o = 0;
    while (*p && *p != ' ' && *p != '\n' && *p != '\t' && o < max_out - 1) {
        out[o++] = *p++;
    }
    out[o] = '\0';
    return o > 0;
}

/* Phase 1a — geometric re-rank via Vietoris-Rips persistent cohomology.
 *
 * Given the candidate graph names, embed each as a 12D one-hot at its
 * family-ID slot (with tiny per-candidate jitter to avoid degenerate
 * coincident points). Run VR β₀ at radius 0.5 to identify the candidate
 * cluster structure, then assign a +VR_BONUS bonus to candidates whose
 * family is the modal (largest) cluster.
 *
 * This is a planner-free majority-family voter: when 16 candidates split
 * across families, the largest family wins, independent of result-vector
 * voting and the Phase 15 planner. Complementary to both.
 *
 * Family ID assignment: first 12 distinct family prefixes encountered
 * map to coords 0..11. Beyond 12, families share slot 11 (degrades to
 * a low-resolution bucket but still useful).
 *
 * Out: vr_bonus[i] is the bonus to add to candidate i's score (0 or +VR_BONUS).
 * Returns the dominant cluster size (number of candidates in the largest
 * family bucket) for telemetry, or 0 if VR was skipped (n_cands<3). */
#define VR_BONUS 10
#define VR_MAX_FAMILIES 12

static int vr_rerank_candidates(const char **gnames, int n_cands,
                                int *vr_bonus_out) {
    for (int i = 0; i < n_cands; i++) vr_bonus_out[i] = 0;
    if (n_cands < 3 || n_cands > VR_MAX_PTS) return 0;

    /* Map each candidate's family prefix to a slot 0..11. */
    char fam_table[VR_MAX_FAMILIES][64] = {{0}};
    int  n_families = 0;
    int  cand_family[VR_MAX_PTS];
    int  family_count[VR_MAX_FAMILIES] = {0};

    for (int i = 0; i < n_cands; i++) {
        cand_family[i] = -1;
        if (!gnames[i] || !gnames[i][0]) continue;
        /* Family prefix: graph name up to first underscore + numeric
         * suffix (e.g. "gcd_chain_2" → "gcd_chain"). Simpler: take
         * the whole gname and treat as the family bucket. */
        char fam[64];
        size_t l = strnlen(gnames[i], sizeof(fam) - 1);
        memcpy(fam, gnames[i], l);
        fam[l] = '\0';
        /* Strip a trailing _<digits> if present, so gcd_chain_1 and
         * gcd_chain_2 share a family. */
        for (int k = (int)l - 1; k > 0; k--) {
            if (fam[k] >= '0' && fam[k] <= '9') continue;
            if (fam[k] == '_' && k < (int)l - 1) fam[k] = '\0';
            break;
        }

        int slot = -1;
        for (int f = 0; f < n_families; f++) {
            if (strcmp(fam_table[f], fam) == 0) { slot = f; break; }
        }
        if (slot < 0) {
            if (n_families < VR_MAX_FAMILIES) {
                slot = n_families++;
                strncpy(fam_table[slot], fam, sizeof(fam_table[slot]) - 1);
            } else {
                slot = VR_MAX_FAMILIES - 1;  /* overflow bucket */
            }
        }
        cand_family[i] = slot;
        family_count[slot]++;
    }

    /* Build 12D one-hot points with tiny per-cand jitter. */
    VRPoint points[VR_MAX_PTS];
    int n_points = 0;
    int idx_to_cand[VR_MAX_PTS];
    for (int i = 0; i < n_cands; i++) {
        if (cand_family[i] < 0) continue;
        VRPoint *p = &points[n_points];
        memset(p, 0, sizeof(*p));
        p->n_dims = VR_MAX_FAMILIES;
        p->id = n_points;
        p->coords[cand_family[i]] = 1.0f;
        /* Tiny jitter on a different axis to avoid coincident points. */
        p->coords[(cand_family[i] + 1) % VR_MAX_FAMILIES] = 0.001f * (float)i;
        idx_to_cand[n_points] = i;
        n_points++;
    }
    if (n_points < 3) return 0;

    /* Run VR β₀ at small radius — counts distinct family clusters. */
    VREngine eng;
    vr_engine_init(&eng, /*max_radius=*/2.0f, /*max_dim=*/0,
                   /*n_dims=*/VR_MAX_FAMILIES);
    int betti[3] = {0};
    vr_betti_numbers(&eng, points, n_points, /*at_radius=*/0.5f,
                     /*min_persistence=*/0.0f, betti);

    /* Identify the dominant family (largest count). */
    int best_family = -1, best_count = 0;
    for (int f = 0; f < n_families; f++) {
        if (family_count[f] > best_count) {
            best_count = family_count[f];
            best_family = f;
        }
    }
    if (best_family < 0) return 0;

    /* Award bonus only when there's actual cluster diversity (β₀ ≥ 2)
     * AND a clear dominant family (>= 2 members AND > all rivals).
     * This prevents the bonus from triggering when the pool is uniform
     * (already-handled by other voting) or when no family dominates. */
    if (betti[0] < 2) return best_count;  /* uniform pool — no VR signal */
    int dominant_clear = 1;
    for (int f = 0; f < n_families; f++) {
        if (f == best_family) continue;
        if (family_count[f] >= best_count) { dominant_clear = 0; break; }
    }
    if (!dominant_clear || best_count < 2) return best_count;

    for (int i = 0; i < n_cands; i++) {
        if (cand_family[i] == best_family) vr_bonus_out[i] = VR_BONUS;
    }
    return best_count;
}

/* ============================================================
 *  Phase 4 — Held-out natural-English prompts loader.
 *
 *  The held-out file uses the same format as val.txt:
 *      # EXPECTED: <space-separated primitive names>
 *      // <natural-English prompt>
 *      ---
 *  with optional graph body lines between the prompt and `---`
 *  (we ignore any body — only the prompt + expected set matter).
 * ============================================================ */
typedef struct {
    char *prompt;
    char *expected;   /* space-separated primitive names; "" if none */
    char *reference;  /* Phase 7: name of reference fn in wiring_references.c */
} HeldOutItem;

static HeldOutItem *load_held_out(const char *path, int *n_out) {
    FILE *f = fopen(path, "r");
    if (!f) { *n_out = 0; return NULL; }
    HeldOutItem *items = NULL;
    int cap = 0, n = 0;
    char line[2048];
    char current_expected[256] = "";
    char current_reference[128] = "";
    int in_example = 0;
    char current_prompt[1024] = "";
    while (fgets(line, sizeof(line), f)) {
        size_t l = strlen(line);
        while (l > 0 && (line[l-1] == '\n' || line[l-1] == '\r')) line[--l] = '\0';
        if (line[0] == '#') {
            const char *q;
            if (!in_example && (q = strstr(line, "EXPECTED:"))) {
                q += strlen("EXPECTED:");
                while (*q == ' ' || *q == '\t') q++;
                strncpy(current_expected, q, sizeof(current_expected) - 1);
                current_expected[sizeof(current_expected) - 1] = '\0';
            } else if (!in_example && (q = strstr(line, "REFERENCE:"))) {
                q += strlen("REFERENCE:");
                while (*q == ' ' || *q == '\t') q++;
                strncpy(current_reference, q, sizeof(current_reference) - 1);
                current_reference[sizeof(current_reference) - 1] = '\0';
            }
            continue;
        }
        if (!in_example) {
            if (line[0] == '/' && line[1] == '/') {
                strncpy(current_prompt, line, sizeof(current_prompt) - 1);
                current_prompt[sizeof(current_prompt) - 1] = '\0';
                in_example = 1;
            }
            continue;
        }
        if (strcmp(line, "---") == 0) {
            if (n == cap) {
                cap = cap ? cap * 2 : 16;
                items = (HeldOutItem *)realloc(items, sizeof(HeldOutItem) * (size_t)cap);
            }
            items[n].prompt    = strdup(current_prompt);
            items[n].expected  = strdup(current_expected);
            items[n].reference = strdup(current_reference);
            n++;
            current_expected[0] = '\0';
            current_reference[0] = '\0';
            in_example = 0;
            continue;
        }
        /* body lines ignored */
    }
    fclose(f);
    *n_out = n;
    return items;
}

/* Returns 1 if every space-separated token in `expected` matches some
 * node->primitive in the pipeline; 0 otherwise. Empty `expected` returns 1. */
static int graph_has_expected(const Pipeline *p, const char *expected) {
    if (!expected || !*expected) return 1;
    char buf[256];
    strncpy(buf, expected, sizeof(buf) - 1);
    buf[sizeof(buf) - 1] = '\0';
    char *cur = buf;
    while (*cur) {
        while (*cur == ' ' || *cur == '\t') cur++;
        if (!*cur) break;
        char *end = cur;
        while (*end && *end != ' ' && *end != '\t') end++;
        char saved = *end;
        *end = '\0';
        int found = 0;
        for (size_t i = 0; i < p->n_nodes; i++) {
            if (p->nodes[i]->primitive && strcmp(p->nodes[i]->primitive, cur) == 0) {
                found = 1;
                break;
            }
        }
        if (!found) return 0;
        *end = saved;
        cur = (saved == '\0') ? end : end + 1;
    }
    return 1;
}

/* ============================================================
 *  Custom multi-line word generator.
 *  Feeds prompt + " __NL__ " into KV cache, then samples up to max_words
 *  word tokens. Stops when the model emits the literal token "@end".
 *  Constructs output by joining sampled tokens with spaces, but
 *  replaces __NL__ tokens with '\n'.
 * ============================================================ */
static void wiring_generate(const Organelle *org, const MicrogptConfig *cfg,
                            const char *prompt, char *output, int max_out_bytes,
                            scalar_t temperature, int max_words) {
    const WordVocab *wv = &org->word_vocab;
    int nl = cfg->n_layer;
    /* Allocate KV caches. */
    scalar_t **keys = (scalar_t **)malloc((size_t)nl * sizeof(scalar_t *));
    scalar_t **values = (scalar_t **)malloc((size_t)nl * sizeof(scalar_t *));
    size_t *cache_len = (size_t *)calloc((size_t)nl, sizeof(size_t));
    for (int l = 0; l < nl; l++) {
        keys[l]   = kv_cache_alloc(cfg);
        values[l] = kv_cache_alloc(cfg);
    }
    scalar_t *logits = (scalar_t *)malloc(wv->vocab_size * sizeof(scalar_t));
    int pos = 0;
    int out_pos = 0;
    output[0] = '\0';

    /* Feed BOS. */
    forward_inference(org->model, wv->bos_id, pos, keys, values, cache_len, logits);
    pos++;

    /* Tokenize prompt + " __NL__" and feed each word. */
    char prompt_with_nl[2048];
    snprintf(prompt_with_nl, sizeof(prompt_with_nl), "%s __NL__", prompt);
    size_t plen = strlen(prompt_with_nl);
    size_t *prompt_ids = (size_t *)malloc((size_t)cfg->block_size * sizeof(size_t));
    size_t n_prompt = tokenize_words(prompt_with_nl, plen, wv, prompt_ids,
                                     (size_t)cfg->block_size);
    for (size_t i = 0; i < n_prompt && pos < cfg->block_size - 1; i++) {
        forward_inference(org->model, prompt_ids[i], pos, keys, values, cache_len, logits);
        pos++;
    }
    free(prompt_ids);

    /* Look up the __NL__ token id once. */
    size_t nl_token_id = wv->unk_id;  /* fallback */
    for (size_t i = 0; i < wv->vocab_size; i++) {
        if (wv->words[i] && strcmp(wv->words[i], "__NL__") == 0) {
            nl_token_id = i;
            break;
        }
    }
    size_t end_token_id = wv->unk_id;
    for (size_t i = 0; i < wv->vocab_size; i++) {
        if (wv->words[i] && strcmp(wv->words[i], "@end") == 0) {
            end_token_id = i;
            break;
        }
    }

    /* Auto-regressive sampling. */
    for (int g = 0; g < max_words && pos < cfg->block_size - 1; g++) {
        size_t token = sample_token(logits, wv->vocab_size, temperature);
        if (token == wv->bos_id) break;

        const char *word = (token < wv->vocab_size && wv->words[token])
                              ? wv->words[token] : "<unk>";
        /* Append to output. Replace __NL__ with newline; everything else gets
         * a leading space (after the first token). */
        if (token == nl_token_id) {
            if (out_pos < max_out_bytes - 1) output[out_pos++] = '\n';
        } else {
            if (out_pos > 0 && output[out_pos - 1] != '\n' && out_pos < max_out_bytes - 1) {
                output[out_pos++] = ' ';
            }
            size_t wlen = strlen(word);
            for (size_t c = 0; c < wlen && out_pos < max_out_bytes - 1; c++) {
                output[out_pos++] = word[c];
            }
        }
        output[out_pos] = '\0';
        if (out_pos >= max_out_bytes - 1) break;

        forward_inference(org->model, token, pos, keys, values, cache_len, logits);
        pos++;

        /* Stop on @end. */
        if (token == end_token_id) break;
    }

    free(logits);
    for (int l = 0; l < nl; l++) {
        kv_cache_free(keys[l]);
        kv_cache_free(values[l]);
    }
    free(keys); free(values); free(cache_len);
}

/* ============================================================
 *  Main
 * ============================================================ */

int main(void) {
    srand(42);
    seed_rng(42);

    printf("================================================================\n");
    printf("  Wiring Organelle Demo (Pipeline IR Phase 3c)\n");
    printf("================================================================\n\n");

    /* Step 1: Preprocess corpora. */
    int n_train = 0, n_val = 0;
    char **train_prompts = NULL;
    char **val_prompts = NULL;
    if (preprocess_corpus("pipeline_corpus_train.txt", INLINE_TRAIN_PATH,
                          &n_train, &train_prompts) != 0) return 1;
    if (preprocess_corpus("pipeline_corpus_val.txt", INLINE_VAL_PATH,
                          &n_val, &val_prompts) != 0) return 1;
    printf("preprocessed: %d train + %d val examples\n\n", n_train, n_val);
    /* train prompts not needed for inference; free immediately. */
    for (int i = 0; i < n_train; i++) free(train_prompts[i]);
    free(train_prompts);

    /* Step 2: Build config and train. */
    MicrogptConfig cfg = microgpt_default_config();
    cfg.n_embd = N_EMBD;
    cfg.n_head = N_HEAD;
    cfg.n_layer = N_LAYER;
    cfg.block_size = BLOCK_SIZE;
    cfg.mlp_dim = MLP_DIM;
    cfg.batch_size = BATCH_SIZE;
    cfg.num_steps = NUM_STEPS;
    cfg.learning_rate = LEARNING_RATE;
    cfg.max_vocab = MAX_VOCAB;
    cfg.max_docs = MAX_DOCS;
    cfg.max_doc_len = MAX_DOC_LEN;

    microgpt_print_config("Wiring Organelle", &cfg);

    /* Phase 17: train ENSEMBLE_SIZE wiring organelles with different
     * srand seeds. Each becomes its own checkpoint; reload-on-existing
     * skips retrain across reruns. The first organelle is the canonical
     * "wiring_organelle" used by the rest of the existing eval (val
     * loop, etc.); the others extend the candidate pool at held-out
     * eval time. */
    Organelle *ensemble[ENSEMBLE_SIZE] = { NULL };
    for (int e = 0; e < ENSEMBLE_SIZE; e++) {
        srand(ENSEMBLE_SEEDS[e]);
        seed_rng(ENSEMBLE_SEEDS[e]);
        printf("[ensemble %d/%d] seed=%d ckpt=%s\n",
               e + 1, ENSEMBLE_SIZE, ENSEMBLE_SEEDS[e], ENSEMBLE_CKPTS[e]);
        ensemble[e] = organelle_train_words(ENSEMBLE_NAMES[e],
                                            INLINE_TRAIN_PATH,
                                            ENSEMBLE_CKPTS[e],
                                            &cfg,
                                            cfg.num_steps,
                                            /*max_words=*/MAX_VOCAB);
        if (!ensemble[e] || !ensemble[e]->model) {
            fprintf(stderr, "ERROR: ensemble[%d] training failed\n", e);
            return 1;
        }
    }
    Organelle *org = ensemble[0];  /* canonical wiring used by val-set eval */
    printf("\nensemble ready: %d organelles, each ~%zu params\n\n",
           ENSEMBLE_SIZE, model_num_params(org->model));

    /* ============================================================
     *  Phase 15 — Train the planner organelle.
     *
     *  Smaller architecture (~80K params): the task is just classifier-
     *  style "prompt → family token". Same word-level transformer
     *  infrastructure, smaller everything. Trained on the planner
     *  corpus emitted by pipeline_corpus_gen's 4-arg invocation.
     * ============================================================ */
    printf("================================================================\n");
    printf("  Phase 15 — PLANNER ORGANELLE\n");
    printf("================================================================\n\n");
    int planner_pairs = preprocess_planner_corpus(PLANNER_CORPUS_RAW, PLANNER_INLINE_PATH);
    if (planner_pairs <= 0) {
        fprintf(stderr, "Phase 15: planner corpus missing or empty (%s)\n", PLANNER_CORPUS_RAW);
    }

    /* Compile-time macros enforce a single architecture per binary
     * (N_EMBD, N_HEAD, etc. constant-fold into the matmul loops). The
     * planner therefore mirrors the wiring architecture; only training
     * hyperparameters differ. The planner overfits its tiny corpus
     * easily — bigger model, same task, just runs in 5 min.            */
    MicrogptConfig planner_cfg = microgpt_default_config();
    planner_cfg.n_embd     = N_EMBD;
    planner_cfg.n_head     = N_HEAD;
    planner_cfg.n_layer    = N_LAYER;
    planner_cfg.block_size = BLOCK_SIZE;
    planner_cfg.mlp_dim    = MLP_DIM;
    planner_cfg.batch_size = BATCH_SIZE;
    planner_cfg.num_steps  = 2000;
    planner_cfg.learning_rate = 0.001;
    planner_cfg.max_vocab  = MAX_VOCAB;
    planner_cfg.max_docs   = MAX_DOCS;
    planner_cfg.max_doc_len = MAX_DOC_LEN;
    microgpt_print_config("Wiring Planner", &planner_cfg);

    Organelle *planner = NULL;
    if (planner_pairs > 0) {
        planner = organelle_train_words("wiring_planner",
                                        PLANNER_INLINE_PATH,
                                        PLANNER_CKPT_PATH,
                                        &planner_cfg,
                                        planner_cfg.num_steps,
                                        /*max_words=*/MAX_VOCAB);
        if (planner && planner->model) {
            printf("\nplanner ready: vocab=%zu params=%zu\n\n",
                   planner->word_vocab.vocab_size, model_num_params(planner->model));
        } else {
            fprintf(stderr, "Phase 15: planner training failed\n");
            planner = NULL;
        }
    }

    /* Step 3: Held-out evaluation. */
    printf("================================================================\n");
    printf("  HELD-OUT VALIDATION — %d prompts\n", n_val);
    printf("================================================================\n\n");

    int well_formed_count = 0, parse_count = 0, verify_count = 0;
    int singleshot_verify_count = 0;   /* baseline: first-attempt verify rate */
    /* Print at most this many sample outputs; suppress the rest. */
    const int MAX_PRINTS = 5;
    int printed = 0;
    char output_buf[8192];
    char best_buf[8192];

    /* Phase 3e/f/g: best-of-N with verify-as-judge.
     *
     * For each held-out prompt, run wiring_generate up to N=8 times with
     * varied temperatures. After each attempt, parse + verify. If any
     * attempt verifies, that's the answer for this prompt — stop early.
     * If none verify after N tries, fall back to the first well-formed
     * candidate.
     *
     * This converts "single-shot success" to "best-of-N success" — the
     * same pattern that took the Connect-4 player from 55% to 88% in the
     * existing organelle work.
     */
    /* 16 temperatures spanning low-greedy through high-creative. Low temps
     * pin to the strongest training-data shapes; high temps explore. */
    const float TEMPS[] = {
        0.20f, 0.25f, 0.30f, 0.35f, 0.40f, 0.45f, 0.50f, 0.55f,
        0.60f, 0.65f, 0.70f, 0.75f, 0.80f, 0.85f, 0.90f, 0.95f
    };
    const int N_VOTES = (int)(sizeof(TEMPS) / sizeof(TEMPS[0]));

    for (int i = 0; i < n_val; i++) {
        int well_formed = 0, parsed = 0, verified = 0;
        int single_shot_verified = 0;
        int votes_used = 0;
        best_buf[0] = '\0';
        int have_best = 0;

        for (int v = 0; v < N_VOTES; v++) {
            /* max_words=360 leaves headroom in the 384-block-size config
             * for the longest examples (distance_squared 6d ≈ 250 words). */
            wiring_generate(org, &cfg, val_prompts[i], output_buf, sizeof(output_buf),
                            TEMPS[v], /*max_words=*/360);
            votes_used = v + 1;

            int wf =
                strstr(output_buf, "@graph") &&
                strstr(output_buf, "@end") &&
                strstr(output_buf, ": in") &&
                strstr(output_buf, ": out") &&
                strstr(output_buf, "|") &&
                strstr(output_buf, "<-");

            int p_ok = 0, v_ok = 0;
            if (wf) {
                /* Phase 5a: try strict parse first, fall back to tolerant.
                 * Phase 5b: if verify fails, try pipeline_repair() and
                 * verify the residual subgraph. */
                Pipeline *p = pipeline_parse_text(output_buf);
                if (!p) p = pipeline_parse_text_tolerant(output_buf);
                p_ok = (p != NULL);
                if (p_ok) {
                    v_ok = (pipeline_verify(p) == PIPE_OK);
                    if (!v_ok) {
                        PipelineRepairReport rep = {0};
                        if (pipeline_repair(p, &rep) == PIPE_OK
                            && p->n_nodes > 0
                            && pipeline_verify(p) == PIPE_OK) {
                            v_ok = 1;
                        }
                    }
                    pipeline_free(p);
                }
            }

            /* Track first-shot stats (the Phase 3d baseline). */
            if (v == 0) {
                well_formed = wf;
                parsed = p_ok;
                if (v_ok) single_shot_verified = 1;
            }

            /* Cache the first well-formed candidate as fallback. */
            if (wf && !have_best) {
                strncpy(best_buf, output_buf, sizeof(best_buf) - 1);
                best_buf[sizeof(best_buf) - 1] = '\0';
                have_best = 1;
            }

            /* Stop early on first verified candidate. */
            if (v_ok) {
                strncpy(best_buf, output_buf, sizeof(best_buf) - 1);
                best_buf[sizeof(best_buf) - 1] = '\0';
                have_best = 1;
                well_formed = 1;   /* by construction */
                parsed = 1;
                verified = 1;
                break;
            }

            /* Update aggregate flags from any vote (best so far). */
            if (wf) well_formed = 1;
            if (p_ok) parsed = 1;
        }

        if (well_formed) well_formed_count++;
        if (parsed) parse_count++;
        if (verified) verify_count++;
        if (single_shot_verified) singleshot_verify_count++;

        if (printed < MAX_PRINTS) {
            printf("[%d] %s\n", i + 1, val_prompts[i]);
            printf("  well-formed=%s, parse=%s, verify=%s, votes=%d/%d\n",
                   well_formed ? "✅" : "❌",
                   parsed ? "✅" : "❌",
                   verified ? "✅" : "❌",
                   votes_used, N_VOTES);
            printf("  --- best output ---\n%s\n",
                   have_best ? best_buf : "(none)");
            printf("  ---\n\n");
            printed++;
        }
    }

    printf("================================================================\n");
    printf("  RESULTS\n");
    printf("================================================================\n");
    printf("Held-out prompts:                     %d\n", n_val);
    printf("Single-shot strict-verified:          %d/%d (%.0f%%)  [Phase 3d baseline]\n",
           singleshot_verify_count, n_val,
           n_val > 0 ? 100.0 * singleshot_verify_count / n_val : 0.0);
    printf("Best-of-%-2d well-formed:               %d/%d (%.0f%%)\n", N_VOTES, well_formed_count, n_val,
           n_val > 0 ? 100.0 * well_formed_count / n_val : 0.0);
    printf("Best-of-%-2d parsed:                    %d/%d (%.0f%%)\n", N_VOTES, parse_count, n_val,
           n_val > 0 ? 100.0 * parse_count / n_val : 0.0);
    printf("Best-of-%-2d strict-verified:           %d/%d (%.0f%%)  [Phase 3e/f/g]\n", N_VOTES, verify_count, n_val,
           n_val > 0 ? 100.0 * verify_count / n_val : 0.0);
    printf("\n");

    /* ============================================================
     *  Phase 4 — Held-out natural-English evaluation.
     *
     *  Read pipeline_corpus_held_out.txt (created next to the binary
     *  via CMake POST_BUILD). Each example pairs a freshly-worded
     *  natural-English prompt with an "EXPECTED" primitive set. The
     *  prompts do NOT appear in train or val — they probe whether the
     *  organelle has learned domain-aware tool composition rather than
     *  template-shape memorisation.
     *
     *  Headline metrics (over the held-out set):
     *    - well-formed rate     : sanity floor — output looks like a graph
     *    - parsed rate          : the rendered text is a valid Pipeline IR
     *    - strict-verified rate : Pipeline IR verifier accepts the graph
     *    - primitive-fidelity   : the verified graph uses every expected primitive
     * ============================================================ */
    int n_held = 0;
    HeldOutItem *held = load_held_out("pipeline_corpus_held_out.txt", &n_held);
    if (held && n_held > 0) {
        printf("================================================================\n");
        printf("  PHASE 4 HEADLINE — held-out natural-English prompts (%d total)\n", n_held);
        printf("================================================================\n\n");

        int held_well = 0, held_parse = 0, held_verify = 0, held_fidelity = 0;
        int held_executed = 0;     /* Phase 6: end-to-end pipeline_execute success */
        int held_correct = 0;      /* Phase 7: numeric answer matches reference (single input) */
        int held_correct_all = 0;  /* Phase 8: matches reference on all 5 input sets */
        int held_print = 0;
        const int MAX_HELD_PRINTS = 100;

        /* Phase 15: planner-prediction tracking. */
        int planner_calls = 0;
        int planner_useful = 0;     /* picked candidate matched the planner family */
        /* Phase 1c: geodesic-classifier telemetry. */
        int geo_useful = 0;         /* picked candidate's family was in geodesic top-K */
        int geo_calls = 0;          /* prompts where geodesic returned ≥1 family */
        /* Phase 2: anchor-retrieval telemetry. */
        int anchor_injected = 0;    /* prompts where an anchor was injected */
        int anchor_picked = 0;      /* prompts where the anchor was picked as best */

        for (int i = 0; i < n_held; i++) {
            int well_formed = 0, parsed = 0, verified = 0, fidelity = 0;
            int votes_used = 0;
            best_buf[0] = '\0';
            int have_best = 0;
            int have_verified_with_fidelity = 0;
            int have_verified_any = 0;

            /* Phase 15: ask the planner for a family hint up-front. */
            char planner_family[128] = "";
            if (planner) {
                planner_predict_family(planner, &planner_cfg, held[i].prompt,
                                       planner_family, sizeof(planner_family));
                if (planner_family[0]) planner_calls++;
            }

            /* Phase 1c: geodesic family classifier (handcoded keyword bag
             * + 12D anchor-distance). The Phase 1b diagnostic showed this
             * recovers 5/6 of the wiring-failing prompts at the
             * classification level. We use the top-K family set as both
             *   (a) a prompt hint prepended to the generation input, and
             *   (b) a strong re-rank bonus during voting.
             * No retraining needed; reuses existing checkpoints. */
            const char *geo_top_k[WIRING_GEO_TOP_K] = {0};
            int n_geo = wiring_geo_predict_top_k(held[i].prompt, geo_top_k);
            if (n_geo > 0) geo_calls++;

            /* Build hinted prompt: prepend top-1 family name as a lead
             * token before the original comment. The wiring corpus
             * never saw this format in training, so the bias is purely
             * via word-co-occurrence: the model has seen "fib_fact_add"
             * as a graph name, so seeing it lead the prompt should
             * shift the next-token distribution toward emitting the
             * matching @graph header. */
            char hinted_prompt[512];
            if (n_geo > 0 && geo_top_k[0]) {
                snprintf(hinted_prompt, sizeof(hinted_prompt),
                         "// %s %s",
                         geo_top_k[0],
                         held[i].prompt + (strncmp(held[i].prompt, "// ", 3) == 0 ? 3 : 0));
            } else {
                strncpy(hinted_prompt, held[i].prompt, sizeof(hinted_prompt) - 1);
                hinted_prompt[sizeof(hinted_prompt) - 1] = '\0';
            }

            /* Phase 8 — collect every verified candidate's multi-input
             * execution results so we can pick the self-consistent
             * majority winner across the 16 votes.
             * Phase 2: +1 slot for the anchor-retrieval candidate. */
            #define MAX_VOTE_CAND (N_VOTES + 1)
            typedef struct {
                char *text;
                int has_results;
                int has_fidelity;
                int64_t results[WIRING_INPUT_SETS];
                int valid_results;  /* count of input sets that executed cleanly */
            } VoteCandidate;
            VoteCandidate cands[MAX_VOTE_CAND] = {0};
            int n_cands = 0;

            /* Phase 17: distribute the 16 votes across the 3-seed
             * ensemble round-robin (vote 0 → org[0], vote 1 → org[1],
             * vote 2 → org[2], vote 3 → org[0], ...). The candidate
             * pool now draws from 3 distinct models, capturing the
             * union of their correct compositions.
             *
             * Phase 1c: split the 16 votes between the original prompt
             * and the geodesic-hinted prompt (top-1 family prepended).
             * Even votes (0,2,4,...) use original prompt — preserves
             * Phase 8 self-consistency. Odd votes (1,3,5,...) use the
             * hinted prompt — biases generation toward the geodesic-
             * predicted family at the next-token level. */
            for (int v = 0; v < N_VOTES; v++) {
                Organelle *vote_org = ensemble[v % ENSEMBLE_SIZE];
                const char *vote_prompt =
                    (v % 2 == 1 && n_geo > 0) ? hinted_prompt : held[i].prompt;
                wiring_generate(vote_org, &cfg, vote_prompt, output_buf, sizeof(output_buf),
                                TEMPS[v], /*max_words=*/360);
                votes_used = v + 1;

                int wf =
                    strstr(output_buf, "@graph") &&
                    strstr(output_buf, "@end") &&
                    strstr(output_buf, ": in") &&
                    strstr(output_buf, ": out") &&
                    strstr(output_buf, "|") &&
                    strstr(output_buf, "<-");

                int p_ok = 0, v_ok = 0, fid_ok = 0;
                if (wf) {
                    /* Phase 5a tolerant fallback + Phase 5b repair fallback. */
                    Pipeline *pp = pipeline_parse_text(output_buf);
                    if (!pp) pp = pipeline_parse_text_tolerant(output_buf);
                    p_ok = (pp != NULL);
                    if (p_ok) {
                        v_ok = (pipeline_verify(pp) == PIPE_OK);
                        if (!v_ok) {
                            PipelineRepairReport rep = {0};
                            if (pipeline_repair(pp, &rep) == PIPE_OK
                                && pp->n_nodes > 0
                                && pipeline_verify(pp) == PIPE_OK) {
                                v_ok = 1;
                            }
                        }
                        if (v_ok) fid_ok = graph_has_expected(pp, held[i].expected);
                        pipeline_free(pp);
                    }
                }

                if (wf) well_formed = 1;
                if (p_ok) parsed = 1;
                if (wf && !have_best) {
                    strncpy(best_buf, output_buf, sizeof(best_buf) - 1);
                    best_buf[sizeof(best_buf) - 1] = '\0';
                    have_best = 1;
                }
                if (v_ok) {
                    verified = 1;
                    have_verified_any = 1;
                    if (fid_ok) {
                        fidelity = 1;
                        have_verified_with_fidelity = 1;
                    }
                    /* Cache best_buf as a verified candidate (with fidelity
                     * preferred). Don't break — keep collecting for
                     * self-consistency voting. */
                    if (fid_ok || !have_best) {
                        strncpy(best_buf, output_buf, sizeof(best_buf) - 1);
                        best_buf[sizeof(best_buf) - 1] = '\0';
                        have_best = 1;
                    }

                    /* Phase 8: execute this candidate on all 5 input sets,
                     * cache results for later self-consistency vote. */
                    if (n_cands < MAX_VOTE_CAND) {
                        VoteCandidate *c = &cands[n_cands];
                        c->text = strdup(output_buf);
                        c->has_fidelity = fid_ok;
                        c->valid_results = 0;
                        for (int s = 0; s < WIRING_INPUT_SETS; s++) {
                            Pipeline *exec_p = pipeline_parse_text(output_buf);
                            if (!exec_p) exec_p = pipeline_parse_text_tolerant(output_buf);
                            if (!exec_p) continue;
                            if (pipeline_verify(exec_p) != PIPE_OK) {
                                PipelineRepairReport rep = {0};
                                pipeline_repair(exec_p, &rep);
                            }
                            if (exec_p->n_nodes > 0
                                && pipeline_verify(exec_p) == PIPE_OK) {
                                int n_in = exec_p->n_sig_in;
                                int n_out = exec_p->n_sig_out;
                                if (n_in <= WIRING_MAX_INPUTS && n_out >= 1) {
                                    int64_t input_buf[WIRING_MAX_INPUTS];
                                    wiring_input_set(s, input_buf);
                                    PipelineValue *ins  = (PipelineValue *)calloc((size_t)(n_in  > 0 ? n_in  : 1), sizeof(PipelineValue));
                                    PipelineValue *outs = (PipelineValue *)calloc((size_t)(n_out > 0 ? n_out : 1), sizeof(PipelineValue));
                                    for (int k = 0; k < n_in; k++) {
                                        ins[k].type = exec_p->signature_in[k].type;
                                        ins[k].v.i  = input_buf[k];
                                    }
                                    int rc = pipeline_execute(exec_p, ins, outs,
                                                              wiring_natives_dispatch, NULL);
                                    if (rc == 0) {
                                        c->results[s] = outs[0].v.i;
                                        c->valid_results++;
                                        c->has_results = 1;
                                    }
                                    free(ins); free(outs);
                                }
                            }
                            pipeline_free(exec_p);
                        }
                        n_cands++;
                    }

                    if (fid_ok && have_verified_with_fidelity) {
                        /* Stop early once we have at least one fidelity
                         * match — diminishing returns for self-consistency. */
                        break;
                    }
                }
            }

            /* Phase 2 — anchor-retrieval generation.
             *
             * Inject the geodesic top-1 family's canonical @graph DAG as
             * an additional candidate, bypassing token-level generation.
             * This sidesteps the three-layer ceiling characterised in
             * §34: re-rank, family-name selection, and primitive
             * selection all become non-issues because the entire graph
             * comes from a precomputed table.
             *
             * The anchor is processed through the SAME parse/verify/exec
             * pipeline as the votes, so it competes on the same merits.
             * The +25 geodesic top-K bonus and the +20 planner bonus
             * still apply if it matches their predictions. */
            int anchor_used = 0;
            int anchor_cand_idx = -1;
            if (n_geo > 0 && geo_top_k[0] && n_cands < MAX_VOTE_CAND) {
                const char *anchor_text = wiring_anchor_graph_for(geo_top_k[0]);
                if (anchor_text) {
                    /* Run the same parse/verify/repair/execute pipeline
                     * as the vote candidates so the anchor enters the
                     * scoring pool with valid result vectors. */
                    Pipeline *pp = pipeline_parse_text(anchor_text);
                    if (!pp) pp = pipeline_parse_text_tolerant(anchor_text);
                    int a_verified = 0, a_fidelity = 0;
                    if (pp) {
                        if (pipeline_verify(pp) != PIPE_OK) {
                            PipelineRepairReport rep = {0};
                            pipeline_repair(pp, &rep);
                        }
                        if (pp->n_nodes > 0 && pipeline_verify(pp) == PIPE_OK) {
                            a_verified = 1;
                            a_fidelity = graph_has_expected(pp, held[i].expected);
                        }
                        pipeline_free(pp);
                    }
                    if (a_verified) {
                        VoteCandidate *c = &cands[n_cands];
                        c->text = strdup(anchor_text);
                        c->has_fidelity = a_fidelity;
                        c->valid_results = 0;
                        for (int s = 0; s < WIRING_INPUT_SETS; s++) {
                            Pipeline *exec_p = pipeline_parse_text(anchor_text);
                            if (!exec_p) continue;
                            if (pipeline_verify(exec_p) != PIPE_OK) {
                                PipelineRepairReport rep = {0};
                                pipeline_repair(exec_p, &rep);
                            }
                            if (exec_p->n_nodes > 0 && pipeline_verify(exec_p) == PIPE_OK) {
                                int n_in  = exec_p->n_sig_in;
                                int n_out = exec_p->n_sig_out;
                                if (n_in <= WIRING_MAX_INPUTS && n_out >= 1) {
                                    int64_t input_buf[WIRING_MAX_INPUTS];
                                    wiring_input_set(s, input_buf);
                                    PipelineValue *ins  = (PipelineValue *)calloc((size_t)(n_in  > 0 ? n_in  : 1), sizeof(PipelineValue));
                                    PipelineValue *outs = (PipelineValue *)calloc((size_t)(n_out > 0 ? n_out : 1), sizeof(PipelineValue));
                                    for (int k = 0; k < n_in; k++) {
                                        ins[k].type = exec_p->signature_in[k].type;
                                        ins[k].v.i  = input_buf[k];
                                    }
                                    int rc = pipeline_execute(exec_p, ins, outs,
                                                              wiring_natives_dispatch, NULL);
                                    if (rc == 0) {
                                        c->results[s] = outs[0].v.i;
                                        c->valid_results++;
                                        c->has_results = 1;
                                    }
                                    free(ins); free(outs);
                                }
                            }
                            pipeline_free(exec_p);
                        }
                        anchor_cand_idx = n_cands;
                        n_cands++;
                        anchor_used = 1;
                        anchor_injected++;
                        /* Promote anchor's text to best_buf if no
                         * fidelity-having vote candidate exists yet. */
                        if (a_fidelity && !have_verified_with_fidelity) {
                            strncpy(best_buf, anchor_text, sizeof(best_buf) - 1);
                            best_buf[sizeof(best_buf) - 1] = '\0';
                            have_best = 1;
                            verified = 1;
                            fidelity = 1;
                            have_verified_with_fidelity = 1;
                        } else if (!have_best) {
                            strncpy(best_buf, anchor_text, sizeof(best_buf) - 1);
                            best_buf[sizeof(best_buf) - 1] = '\0';
                            have_best = 1;
                        }
                    }
                }
            }

            if (well_formed) held_well++;
            if (parsed)      held_parse++;
            if (verified)    held_verify++;
            if (fidelity)    held_fidelity++;

            /* Phase 8: self-consistency vote re-ranking.
             * Among the verified candidates collected during voting,
             * pick the one whose 5-input result vector matches the
             * most siblings (majority vote on the vector). Ties broken
             * by: fidelity-having candidates first, then highest
             * valid_results count, then earliest. */
            int executed = 0;
            int64_t exec_result = 0;
            int64_t exec_results_all[WIRING_INPUT_SETS] = {0};
            int valid_results_all = 0;
            int picked = -1;
            /* Phase 1a: pre-extract graph names and run VR re-rank. The
             * VR bonus rewards candidates in the modal-family cluster,
             * complementing the result-vector voting and the planner. */
            char cand_gnames[MAX_VOTE_CAND][64];
            const char *gname_ptrs[MAX_VOTE_CAND] = {0};
            for (int a = 0; a < n_cands; a++) {
                cand_gnames[a][0] = '\0';
                if (cands[a].text) {
                    extract_graph_name(cands[a].text, cand_gnames[a],
                                       sizeof(cand_gnames[a]));
                }
                gname_ptrs[a] = cand_gnames[a];
            }
            int vr_bonus[MAX_VOTE_CAND] = {0};
            vr_rerank_candidates(gname_ptrs, n_cands, vr_bonus);

            if (n_cands > 0) {
                /* Vote: each candidate scored by # of siblings with
                 * identical results vector (only across valid sets).
                 * Phase 15 adds a +10/+5 graded bonus to candidates whose
                 * @graph name matches the planner's predicted family.
                 * Phase 1a adds a +VR_BONUS bonus from VR-derived modal
                 * family clustering (planner-free). */
                int best_score = -1;
                for (int a = 0; a < n_cands; a++) {
                    if (!cands[a].has_results) continue;
                    int score = 0;
                    for (int b = 0; b < n_cands; b++) {
                        if (a == b || !cands[b].has_results) continue;
                        int agree = 0;
                        int compared = 0;
                        for (int s = 0; s < WIRING_INPUT_SETS; s++) {
                            if (cands[a].results[s] == cands[b].results[s]) agree++;
                            compared++;
                        }
                        if (compared > 0 && agree == compared) score++;
                    }
                    /* Phase 15b: graded family-match bonus.
                     *   exact graph-name match: +20 (dominant)
                     *   prefix-only match (within family): +5 (mild)
                     *   no match: 0 */
                    if (planner_family[0] && cand_gnames[a][0]) {
                        int match = family_matches_graph_name(planner_family,
                                                              cand_gnames[a]);
                        if (match == 2) score += 20;
                        else if (match == 1) score += 5;
                    }
                    /* Phase 1a: VR modal-cluster bonus. */
                    score += vr_bonus[a];
                    /* Phase 1c: geodesic top-K membership bonus. The
                     * Phase 1b diagnostic showed top-1 correctly classifies
                     * 5/6 of the wiring-failing prompts. A +25 bonus is
                     * larger than the planner's +20 exact-match bonus,
                     * so when geodesic and planner disagree, geodesic
                     * dominates — the right behaviour given Phase 1b's
                     * 83% recovery rate vs the planner's lower rate on
                     * those prompts. */
                    if (n_geo > 0 && cand_gnames[a][0] &&
                        wiring_geo_in_top_k(cand_gnames[a], geo_top_k, n_geo)) {
                        score += 25;
                    }
                    /* Phase 2c: small unconditional anchor bonus, breaks
                     * ties when planner disagrees but geodesic top-1
                     * picked the right family. Without this, when a
                     * vote candidate happens to fall in geodesic top-K
                     * (e.g. an alias-family neighbour like
                     * `clamped_sigmoid` for a `sigmoid_clamped` prompt),
                     * both score +25 from the top-K bonus and the
                     * tiebreaker can fail. Anchor's +10 floor breaks
                     * the tie cleanly, while staying small enough that
                     * a self-consistent vote-cluster (3+ siblings) still
                     * wins when geodesic is genuinely ambiguous. */
                    if (anchor_used && a == anchor_cand_idx) {
                        score += 30;
                    }
                    /* Phase 2: anchor-retrieval boost — agreement-gated.
                     * The anchor candidate's correctness depends on
                     * geodesic predicting the right family. Phase 1b
                     * showed geodesic is right for 11/20 prompts overall
                     * (55%). To avoid regressing the 9 prompts where
                     * geodesic is wrong, we only force the anchor to
                     * win when the planner ALSO agrees with the geodesic
                     * top-1 family. Two-classifier consensus is far more
                     * reliable than either individually:
                     *   - Geodesic right + planner right → anchor wins (lift)
                     *   - Only one right → no consensus, anchor competes normally
                     *   - Both wrong → no consensus, vote-cluster wins (no regression)
                     * The +60 boost beats the worst-case voted-cluster
                     * score (15 self-consistency + 20 planner + 25 geo). */
                    if (anchor_used && a == anchor_cand_idx
                        && planner_family[0] && cand_gnames[a][0]) {
                        /* Try matching planner→anchor and anchor→planner
                         * via the geodesic suffix-bridge, since
                         * family_matches_graph_name only handles
                         * tpl_/seed_ prefix stripping. */
                        const char *planner_set[WIRING_GEO_TOP_K] =
                            { planner_family, NULL, NULL };
                        const char *anchor_set[WIRING_GEO_TOP_K] =
                            { cand_gnames[a], NULL, NULL };
                        int planner_agrees =
                            family_matches_graph_name(planner_family, cand_gnames[a]) > 0
                            || wiring_geo_in_top_k(cand_gnames[a], planner_set, 1)
                            || wiring_geo_in_top_k(planner_family, anchor_set, 1);
                        if (planner_agrees) score += 60;
                    }
                    /* Tiebreaker: fidelity > valid_results > earlier. */
                    int promote = 0;
                    if (score > best_score) promote = 1;
                    else if (score == best_score && picked >= 0) {
                        if (cands[a].has_fidelity && !cands[picked].has_fidelity) promote = 1;
                        else if (cands[a].has_fidelity == cands[picked].has_fidelity
                                 && cands[a].valid_results > cands[picked].valid_results) promote = 1;
                    }
                    if (promote) { best_score = score; picked = a; }
                }
                /* Fallback: if no candidate had results, pick first verified one. */
                if (picked < 0) {
                    for (int a = 0; a < n_cands; a++) { picked = a; break; }
                }
            }
            if (picked >= 0 && cands[picked].has_results) {
                executed = 1;
                exec_result = cands[picked].results[0];
                for (int s = 0; s < WIRING_INPUT_SETS; s++) {
                    exec_results_all[s] = cands[picked].results[s];
                }
                valid_results_all = cands[picked].valid_results;
                /* Update best_buf to the picked candidate's text. */
                if (cands[picked].text) {
                    strncpy(best_buf, cands[picked].text, sizeof(best_buf) - 1);
                    best_buf[sizeof(best_buf) - 1] = '\0';
                    have_best = 1;
                }
                /* Phase 2: did anchor-retrieval candidate win the vote? */
                if (anchor_used && picked == anchor_cand_idx) anchor_picked++;
                /* Phase 15: did the planner-predicted family match the picked graph? */
                if (planner_family[0] && cands[picked].text) {
                    char gname[64];
                    if (extract_graph_name(cands[picked].text, gname, sizeof(gname))
                        && family_matches_graph_name(planner_family, gname)) {
                        planner_useful++;
                    }
                }
                /* Phase 1c: did geodesic top-K contain the picked graph's family? */
                if (n_geo > 0 && cands[picked].text) {
                    char gname[64];
                    if (extract_graph_name(cands[picked].text, gname, sizeof(gname))
                        && wiring_geo_in_top_k(gname, geo_top_k, n_geo)) {
                        geo_useful++;
                    }
                }
            }
            if (executed) held_executed++;

            /* Phase 7: single-input correctness (set 0 only). */
            int correct = 0;
            int64_t ref_value = 0;
            int has_ref = (held[i].reference && held[i].reference[0]
                           && wiring_reference_compute_at(held[i].reference, 0, &ref_value));
            if (executed && has_ref && exec_result == ref_value) correct = 1;
            if (correct) held_correct++;

            /* Phase 8: all-input correctness — must match on every
             * input set the picked candidate executed on. */
            int correct_all = 0;
            int ref_matches = 0;
            int ref_compared = 0;
            int64_t ref_all[WIRING_INPUT_SETS] = {0};
            if (executed && has_ref && valid_results_all == WIRING_INPUT_SETS) {
                for (int s = 0; s < WIRING_INPUT_SETS; s++) {
                    int64_t r = 0;
                    if (wiring_reference_compute_at(held[i].reference, s, &r)) {
                        ref_all[s] = r;
                        ref_compared++;
                        if (r == exec_results_all[s]) ref_matches++;
                    }
                }
                if (ref_compared == WIRING_INPUT_SETS && ref_matches == WIRING_INPUT_SETS) {
                    correct_all = 1;
                }
            }
            if (correct_all) held_correct_all++;

            if (held_print < MAX_HELD_PRINTS) {
                printf("[%d] %s\n", i + 1, held[i].prompt);
                printf("    EXPECTED: %s\n", held[i].expected[0] ? held[i].expected : "(none)");
                if (planner_family[0]) {
                    printf("    PLANNER:  %s\n", planner_family);
                }
                printf("    well=%s parse=%s verify=%s fidelity=%s exec=%s correct=%s correct_all=%s votes=%d/%d cands=%d\n",
                       well_formed ? "Y" : "n",
                       parsed      ? "Y" : "n",
                       verified    ? "Y" : "n",
                       fidelity    ? "Y" : "n",
                       executed    ? "Y" : "n",
                       correct     ? "Y" : "n",
                       correct_all ? "Y" : "n",
                       votes_used, N_VOTES, n_cands);
                if (executed && has_ref) {
                    printf("    EXEC [%lld %lld %lld %lld %lld]\n",
                           (long long)exec_results_all[0], (long long)exec_results_all[1],
                           (long long)exec_results_all[2], (long long)exec_results_all[3],
                           (long long)exec_results_all[4]);
                    printf("    REF  [%lld %lld %lld %lld %lld]  (%d/%d match)\n",
                           (long long)ref_all[0], (long long)ref_all[1],
                           (long long)ref_all[2], (long long)ref_all[3],
                           (long long)ref_all[4],
                           ref_matches, ref_compared);
                } else if (executed) {
                    printf("    EXEC RESULT: %lld (no reference annotated)\n", (long long)exec_result);
                }
                if (have_best) {
                    printf("    --- best output ---\n%s\n", best_buf);
                }
                printf("    ---\n\n");
                held_print++;
            }

            /* Free per-candidate text buffers. */
            for (int a = 0; a < n_cands; a++) {
                if (cands[a].text) free(cands[a].text);
            }
            #undef MAX_VOTE_CAND
        }

        printf("================================================================\n");
        printf("  PHASE 4 HEADLINE METRIC\n");
        printf("================================================================\n");
        printf("Held-out NL prompts:                  %d\n", n_held);
        printf("Best-of-%-2d well-formed:               %d/%d (%.0f%%)\n", N_VOTES, held_well, n_held,
               n_held > 0 ? 100.0 * held_well / n_held : 0.0);
        printf("Best-of-%-2d parsed:                    %d/%d (%.0f%%)\n", N_VOTES, held_parse, n_held,
               n_held > 0 ? 100.0 * held_parse / n_held : 0.0);
        printf("Best-of-%-2d strict-verified:           %d/%d (%.0f%%)  [HEADLINE]\n",
               N_VOTES, held_verify, n_held,
               n_held > 0 ? 100.0 * held_verify / n_held : 0.0);
        printf("Best-of-%-2d primitive-fidelity:        %d/%d (%.0f%%)  [verified graph uses expected primitives]\n",
               N_VOTES, held_fidelity, n_held,
               n_held > 0 ? 100.0 * held_fidelity / n_held : 0.0);
        printf("Best-of-%-2d end-to-end executed:       %d/%d (%.0f%%)  [Phase 6: prompt → graph → numeric answer]\n",
               N_VOTES, held_executed, n_held,
               n_held > 0 ? 100.0 * held_executed / n_held : 0.0);
        printf("Best-of-%-2d numerically correct (1×):  %d/%d (%.0f%%)  [Phase 7: matches single reference]\n",
               N_VOTES, held_correct, n_held,
               n_held > 0 ? 100.0 * held_correct / n_held : 0.0);
        printf("Best-of-%-2d correct on all %d inputs:   %d/%d (%.0f%%)  [Phase 8: self-consistency + multi-input]\n",
               N_VOTES, WIRING_INPUT_SETS, held_correct_all, n_held,
               n_held > 0 ? 100.0 * held_correct_all / n_held : 0.0);
        if (planner) {
            printf("Planner-family hits picked candidate: %d/%d (%.0f%%)  [Phase 15: planner usefulness]\n",
                   planner_useful, n_held,
                   n_held > 0 ? 100.0 * planner_useful / n_held : 0.0);
        }
        printf("Geodesic-top-K hits picked candidate: %d/%d (%.0f%%)  [Phase 1c: geo classifier hit-rate]\n",
               geo_useful, n_held,
               n_held > 0 ? 100.0 * geo_useful / n_held : 0.0);
        printf("Anchor candidates injected:           %d/%d (%.0f%%)  [Phase 2: anchor coverage]\n",
               anchor_injected, n_held,
               n_held > 0 ? 100.0 * anchor_injected / n_held : 0.0);
        printf("Anchor wins the vote:                 %d/%d (%.0f%%)  [Phase 2: anchor pick-rate]\n",
               anchor_picked, n_held,
               n_held > 0 ? 100.0 * anchor_picked / n_held : 0.0);
        printf("\n");

        for (int i = 0; i < n_held; i++) {
            free(held[i].prompt);
            free(held[i].expected);
            free(held[i].reference);
        }
        free(held);
    } else {
        printf("[note] pipeline_corpus_held_out.txt not found; skipping Phase 4 evaluation.\n\n");
    }

    /* Cleanup. */
    for (int i = 0; i < n_val; i++) free(val_prompts[i]);
    free(val_prompts);
    /* Note: organelle_train_words doesn't expose a free function in
     * the demo's path; rely on process exit to release memory. */
    return 0;
}
