/*
 * MicroGPT-C — Wiring Organelle Demo (Pipeline IR Phase 3c)
 *
 * Trains a small word-level Transformer on the templated Pipeline IR
 * corpus generated by tools/pipeline_corpus_gen, then evaluates novel-
 * prompt generation: given a held-out comment line, can the model
 * produce a graph that (a) parses, (b) verifies strictly?
 *
 * This is the headline scientific question for the Pipeline IR series.
 * Answers go into RESEARCH_PIPELINE_IR.md §13.
 *
 * Pipeline:
 *   1. Read the standard `pipeline_corpus_train.txt` and
 *      `pipeline_corpus_val.txt` files (produced by pipeline_corpus_gen
 *      train.txt val.txt).
 *   2. Convert each multi-line example to a single-line form by
 *      replacing internal '\n' with ' __NL__ '. Insert a blank line
 *      between examples for opa_load_docs_multiline.
 *   3. Train via organelle_train_words().
 *   4. For each val prompt: feed prompt + __NL__ token, sample word
 *      tokens until we emit `@end`. Reconstruct the graph text by
 *      replacing __NL__ with newline.
 *   5. Try pipeline_parse_text → pipeline_verify on each generated
 *      graph. Report parse-rate, verify-rate, and three sample outputs.
 *
 * Architecture: 4-layer 96-emb 256-block, 5000 train steps. The V4
 * active-attention stack (PARTIAL_ROPE/ATTN_SINK/QK_NORM) is NOT
 * enabled — prior codegen ablation showed -30pp regression on grammar-
 * rigid generation, and this is grammar-rigid by definition.
 *
 * Copyright (c) 2026 Ajay Soni, Enjector Software Ltd. MIT License.
 */

#define _CRT_SECURE_NO_WARNINGS 1

#include "microgpt.h"
#include "microgpt_organelle.h"
#include "microgpt_pipeline.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef NUM_STEPS
#define NUM_STEPS 5000
#endif

#define INLINE_TRAIN_PATH "wiring_corpus_inline_train.txt"
#define INLINE_VAL_PATH   "wiring_corpus_inline_val.txt"
#define CKPT_PATH         "wiring_organelle.ckpt"

/* ============================================================
 *  Corpus preprocessing — inline each example on one line.
 *  Replaces '\n' with ' __NL__ ' inside each example and writes
 *  examples separated by blank lines so opa_load_docs_multiline
 *  treats each as its own doc.
 * ============================================================ */
static int preprocess_corpus(const char *src_path, const char *dst_path,
                             int *n_examples_out, char ***val_prompts_out) {
    FILE *fin = fopen(src_path, "r");
    if (!fin) { fprintf(stderr, "preprocess: cannot open %s\n", src_path); return -1; }
    FILE *fout = fopen(dst_path, "w");
    if (!fout) { fclose(fin); fprintf(stderr, "preprocess: cannot write %s\n", dst_path); return -1; }

    char **prompts = NULL;
    int n_prompts = 0;
    int n_prompts_cap = 0;

    char line[2048];
    /* State machine. We accumulate one example at a time into `buf`,
     * triggered by a `// ` comment line at the start. The example ends
     * when we encounter `---` on its own line. */
    char *buf = NULL;
    size_t buf_cap = 0;
    size_t buf_len = 0;
    int in_example = 0;
    char current_prompt[1024] = "";

    while (fgets(line, sizeof(line), fin)) {
        /* Strip trailing newline. */
        size_t l = strlen(line);
        while (l > 0 && (line[l-1] == '\n' || line[l-1] == '\r')) line[--l] = '\0';

        /* Skip comment lines that start with `# ` (corpus header). */
        if (line[0] == '#') continue;

        if (!in_example) {
            /* Looking for a `// prompt` start-of-example. */
            if (line[0] == '/' && line[1] == '/') {
                strncpy(current_prompt, line, sizeof(current_prompt) - 1);
                current_prompt[sizeof(current_prompt) - 1] = '\0';
                in_example = 1;
                buf_len = 0;
                /* Append the prompt + __NL__ to the buf. */
                size_t add = strlen(line) + strlen(" __NL__ ") + 1;
                if (buf_len + add >= buf_cap) {
                    buf_cap = buf_cap ? buf_cap * 2 : 4096;
                    while (buf_cap < buf_len + add) buf_cap *= 2;
                    buf = (char *)realloc(buf, buf_cap);
                }
                buf_len += (size_t)snprintf(buf + buf_len, buf_cap - buf_len,
                                            "%s __NL__ ", line);
            }
            /* Otherwise skip blank/junk between examples. */
            continue;
        }

        /* Inside an example. End of example marker = `---`. */
        if (strcmp(line, "---") == 0) {
            /* Write inline example to output. */
            fprintf(fout, "%s\n\n", buf);
            /* Capture prompt for held-out evaluation. */
            if (n_prompts == n_prompts_cap) {
                n_prompts_cap = n_prompts_cap ? n_prompts_cap * 2 : 16;
                prompts = (char **)realloc(prompts, sizeof(char *) * (size_t)n_prompts_cap);
            }
            prompts[n_prompts++] = strdup(current_prompt);
            in_example = 0;
            buf_len = 0;
            continue;
        }

        /* Append `line __NL__ ` to buf. */
        size_t add = strlen(line) + strlen(" __NL__ ") + 1;
        if (buf_len + add >= buf_cap) {
            buf_cap = buf_cap ? buf_cap * 2 : 4096;
            while (buf_cap < buf_len + add) buf_cap *= 2;
            buf = (char *)realloc(buf, buf_cap);
        }
        buf_len += (size_t)snprintf(buf + buf_len, buf_cap - buf_len,
                                    "%s __NL__ ", line);
    }

    free(buf);
    fclose(fin);
    fclose(fout);
    *n_examples_out = n_prompts;
    *val_prompts_out = prompts;
    return 0;
}

/* ============================================================
 *  Custom multi-line word generator.
 *  Feeds prompt + " __NL__ " into KV cache, then samples up to max_words
 *  word tokens. Stops when the model emits the literal token "@end".
 *  Constructs output by joining sampled tokens with spaces, but
 *  replaces __NL__ tokens with '\n'.
 * ============================================================ */
static void wiring_generate(const Organelle *org, const MicrogptConfig *cfg,
                            const char *prompt, char *output, int max_out_bytes,
                            scalar_t temperature, int max_words) {
    const WordVocab *wv = &org->word_vocab;
    int nl = cfg->n_layer;
    /* Allocate KV caches. */
    scalar_t **keys = (scalar_t **)malloc((size_t)nl * sizeof(scalar_t *));
    scalar_t **values = (scalar_t **)malloc((size_t)nl * sizeof(scalar_t *));
    size_t *cache_len = (size_t *)calloc((size_t)nl, sizeof(size_t));
    for (int l = 0; l < nl; l++) {
        keys[l]   = kv_cache_alloc(cfg);
        values[l] = kv_cache_alloc(cfg);
    }
    scalar_t *logits = (scalar_t *)malloc(wv->vocab_size * sizeof(scalar_t));
    int pos = 0;
    int out_pos = 0;
    output[0] = '\0';

    /* Feed BOS. */
    forward_inference(org->model, wv->bos_id, pos, keys, values, cache_len, logits);
    pos++;

    /* Tokenize prompt + " __NL__" and feed each word. */
    char prompt_with_nl[2048];
    snprintf(prompt_with_nl, sizeof(prompt_with_nl), "%s __NL__", prompt);
    size_t plen = strlen(prompt_with_nl);
    size_t *prompt_ids = (size_t *)malloc((size_t)cfg->block_size * sizeof(size_t));
    size_t n_prompt = tokenize_words(prompt_with_nl, plen, wv, prompt_ids,
                                     (size_t)cfg->block_size);
    for (size_t i = 0; i < n_prompt && pos < cfg->block_size - 1; i++) {
        forward_inference(org->model, prompt_ids[i], pos, keys, values, cache_len, logits);
        pos++;
    }
    free(prompt_ids);

    /* Look up the __NL__ token id once. */
    size_t nl_token_id = wv->unk_id;  /* fallback */
    for (size_t i = 0; i < wv->vocab_size; i++) {
        if (wv->words[i] && strcmp(wv->words[i], "__NL__") == 0) {
            nl_token_id = i;
            break;
        }
    }
    size_t end_token_id = wv->unk_id;
    for (size_t i = 0; i < wv->vocab_size; i++) {
        if (wv->words[i] && strcmp(wv->words[i], "@end") == 0) {
            end_token_id = i;
            break;
        }
    }

    /* Auto-regressive sampling. */
    for (int g = 0; g < max_words && pos < cfg->block_size - 1; g++) {
        size_t token = sample_token(logits, wv->vocab_size, temperature);
        if (token == wv->bos_id) break;

        const char *word = (token < wv->vocab_size && wv->words[token])
                              ? wv->words[token] : "<unk>";
        /* Append to output. Replace __NL__ with newline; everything else gets
         * a leading space (after the first token). */
        if (token == nl_token_id) {
            if (out_pos < max_out_bytes - 1) output[out_pos++] = '\n';
        } else {
            if (out_pos > 0 && output[out_pos - 1] != '\n' && out_pos < max_out_bytes - 1) {
                output[out_pos++] = ' ';
            }
            size_t wlen = strlen(word);
            for (size_t c = 0; c < wlen && out_pos < max_out_bytes - 1; c++) {
                output[out_pos++] = word[c];
            }
        }
        output[out_pos] = '\0';
        if (out_pos >= max_out_bytes - 1) break;

        forward_inference(org->model, token, pos, keys, values, cache_len, logits);
        pos++;

        /* Stop on @end. */
        if (token == end_token_id) break;
    }

    free(logits);
    for (int l = 0; l < nl; l++) {
        kv_cache_free(keys[l]);
        kv_cache_free(values[l]);
    }
    free(keys); free(values); free(cache_len);
}

/* ============================================================
 *  Main
 * ============================================================ */

int main(void) {
    srand(42);
    seed_rng(42);

    printf("================================================================\n");
    printf("  Wiring Organelle Demo (Pipeline IR Phase 3c)\n");
    printf("================================================================\n\n");

    /* Step 1: Preprocess corpora. */
    int n_train = 0, n_val = 0;
    char **train_prompts = NULL;
    char **val_prompts = NULL;
    if (preprocess_corpus("pipeline_corpus_train.txt", INLINE_TRAIN_PATH,
                          &n_train, &train_prompts) != 0) return 1;
    if (preprocess_corpus("pipeline_corpus_val.txt", INLINE_VAL_PATH,
                          &n_val, &val_prompts) != 0) return 1;
    printf("preprocessed: %d train + %d val examples\n\n", n_train, n_val);
    /* train prompts not needed for inference; free immediately. */
    for (int i = 0; i < n_train; i++) free(train_prompts[i]);
    free(train_prompts);

    /* Step 2: Build config and train. */
    MicrogptConfig cfg = microgpt_default_config();
    cfg.n_embd = N_EMBD;
    cfg.n_head = N_HEAD;
    cfg.n_layer = N_LAYER;
    cfg.block_size = BLOCK_SIZE;
    cfg.mlp_dim = MLP_DIM;
    cfg.batch_size = BATCH_SIZE;
    cfg.num_steps = NUM_STEPS;
    cfg.learning_rate = LEARNING_RATE;
    cfg.max_vocab = MAX_VOCAB;
    cfg.max_docs = MAX_DOCS;
    cfg.max_doc_len = MAX_DOC_LEN;

    microgpt_print_config("Wiring Organelle", &cfg);

    Organelle *org = organelle_train_words("wiring_organelle",
                                           INLINE_TRAIN_PATH,
                                           CKPT_PATH,
                                           &cfg,
                                           cfg.num_steps,
                                           /*max_words=*/MAX_VOCAB);
    if (!org || !org->model) {
        fprintf(stderr, "ERROR: training failed\n");
        return 1;
    }
    printf("\nmodel ready: vocab=%zu params=%zu\n\n",
           org->word_vocab.vocab_size, model_num_params(org->model));

    /* Step 3: Held-out evaluation. */
    printf("================================================================\n");
    printf("  HELD-OUT VALIDATION — %d prompts\n", n_val);
    printf("================================================================\n\n");

    int well_formed_count = 0, parse_count = 0, verify_count = 0;
    int singleshot_verify_count = 0;   /* baseline: first-attempt verify rate */
    /* Print at most this many sample outputs; suppress the rest. */
    const int MAX_PRINTS = 5;
    int printed = 0;
    char output_buf[8192];
    char best_buf[8192];

    /* Phase 3e/f/g: best-of-N with verify-as-judge.
     *
     * For each held-out prompt, run wiring_generate up to N=8 times with
     * varied temperatures. After each attempt, parse + verify. If any
     * attempt verifies, that's the answer for this prompt — stop early.
     * If none verify after N tries, fall back to the first well-formed
     * candidate.
     *
     * This converts "single-shot success" to "best-of-N success" — the
     * same pattern that took the Connect-4 player from 55% to 88% in the
     * existing organelle work.
     */
    /* 16 temperatures spanning low-greedy through high-creative. Low temps
     * pin to the strongest training-data shapes; high temps explore. */
    const float TEMPS[] = {
        0.20f, 0.25f, 0.30f, 0.35f, 0.40f, 0.45f, 0.50f, 0.55f,
        0.60f, 0.65f, 0.70f, 0.75f, 0.80f, 0.85f, 0.90f, 0.95f
    };
    const int N_VOTES = (int)(sizeof(TEMPS) / sizeof(TEMPS[0]));

    for (int i = 0; i < n_val; i++) {
        int well_formed = 0, parsed = 0, verified = 0;
        int single_shot_verified = 0;
        int votes_used = 0;
        best_buf[0] = '\0';
        int have_best = 0;

        for (int v = 0; v < N_VOTES; v++) {
            /* max_words=360 leaves headroom in the 384-block-size config
             * for the longest examples (distance_squared 6d ≈ 250 words). */
            wiring_generate(org, &cfg, val_prompts[i], output_buf, sizeof(output_buf),
                            TEMPS[v], /*max_words=*/360);
            votes_used = v + 1;

            int wf =
                strstr(output_buf, "@graph") &&
                strstr(output_buf, "@end") &&
                strstr(output_buf, ": in") &&
                strstr(output_buf, ": out") &&
                strstr(output_buf, "|") &&
                strstr(output_buf, "<-");

            int p_ok = 0, v_ok = 0;
            if (wf) {
                Pipeline *p = pipeline_parse_text(output_buf);
                p_ok = (p != NULL);
                if (p_ok) {
                    v_ok = (pipeline_verify(p) == PIPE_OK);
                    pipeline_free(p);
                }
            }

            /* Track first-shot stats (the Phase 3d baseline). */
            if (v == 0) {
                well_formed = wf;
                parsed = p_ok;
                if (v_ok) single_shot_verified = 1;
            }

            /* Cache the first well-formed candidate as fallback. */
            if (wf && !have_best) {
                strncpy(best_buf, output_buf, sizeof(best_buf) - 1);
                best_buf[sizeof(best_buf) - 1] = '\0';
                have_best = 1;
            }

            /* Stop early on first verified candidate. */
            if (v_ok) {
                strncpy(best_buf, output_buf, sizeof(best_buf) - 1);
                best_buf[sizeof(best_buf) - 1] = '\0';
                have_best = 1;
                well_formed = 1;   /* by construction */
                parsed = 1;
                verified = 1;
                break;
            }

            /* Update aggregate flags from any vote (best so far). */
            if (wf) well_formed = 1;
            if (p_ok) parsed = 1;
        }

        if (well_formed) well_formed_count++;
        if (parsed) parse_count++;
        if (verified) verify_count++;
        if (single_shot_verified) singleshot_verify_count++;

        if (printed < MAX_PRINTS) {
            printf("[%d] %s\n", i + 1, val_prompts[i]);
            printf("  well-formed=%s, parse=%s, verify=%s, votes=%d/%d\n",
                   well_formed ? "✅" : "❌",
                   parsed ? "✅" : "❌",
                   verified ? "✅" : "❌",
                   votes_used, N_VOTES);
            printf("  --- best output ---\n%s\n",
                   have_best ? best_buf : "(none)");
            printf("  ---\n\n");
            printed++;
        }
    }

    printf("================================================================\n");
    printf("  RESULTS\n");
    printf("================================================================\n");
    printf("Held-out prompts:                     %d\n", n_val);
    printf("Single-shot strict-verified:          %d/%d (%.0f%%)  [Phase 3d baseline]\n",
           singleshot_verify_count, n_val,
           n_val > 0 ? 100.0 * singleshot_verify_count / n_val : 0.0);
    printf("Best-of-%-2d well-formed:               %d/%d (%.0f%%)\n", N_VOTES, well_formed_count, n_val,
           n_val > 0 ? 100.0 * well_formed_count / n_val : 0.0);
    printf("Best-of-%-2d parsed:                    %d/%d (%.0f%%)\n", N_VOTES, parse_count, n_val,
           n_val > 0 ? 100.0 * parse_count / n_val : 0.0);
    printf("Best-of-%-2d strict-verified:           %d/%d (%.0f%%)  [Phase 3e/f/g]\n", N_VOTES, verify_count, n_val,
           n_val > 0 ? 100.0 * verify_count / n_val : 0.0);
    printf("\n");

    /* Cleanup. */
    for (int i = 0; i < n_val; i++) free(val_prompts[i]);
    free(val_prompts);
    /* Note: organelle_train_words doesn't expose a free function in
     * the demo's path; rely on process exit to release memory. */
    return 0;
}
