/*
 * MicroGPT-C — Phase 5 compositional held-out harness
 *
 * Runs `wiring_compositional_search` over the 30-prompt held-out
 * (`pipeline_corpus_compositional_test.txt`), dispatches each verified
 * graph through `pipeline_execute_vm`, scores against the reference
 * oracle in `wiring_references.c`, and reports per-axis stats.
 *
 * Usage:
 *   ./wiring_phase5_harness [held-out-path]
 *
 * Default held-out path: `pipeline_corpus_compositional_test.txt` next
 * to the binary (CMake POST_BUILD copies it for us).
 *
 * Per-axis scoring:
 *   Axis 1 = prompts 1..10 (2-primitive novel pairs)
 *   Axis 2 = prompts 11..20 (3-primitive synonym stress)
 *   Axis 3 = prompts 21..30 (composition + outer transform)
 *
 * Correctness threshold: a prompt counts as "correct" if the executed
 * answer matches the reference for at least 3 of 5 input sets — same
 * threshold as Phase 7.
 *
 * Copyright (c) 2026 Ajay Soni, Enjector Software Ltd. MIT License.
 */

#define _CRT_SECURE_NO_WARNINGS 1

#include "microgpt_pipeline.h"
#include "microgpt_vm.h"
#include "wiring_compositional_search.h"
#include "wiring_primitive_manifest.h"
#include "wiring_references.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <ctype.h>

/* ============================================================
 *  VM-native wrappers around the wiring primitives.
 * ============================================================
 *
 * The wiring_natives.c registry uses `int64_t(int, const int64_t *)`.
 * The VM ABI uses `double(int, const double *)`. One wrapper per
 * manifest entry casts the doubles to int64, computes, and casts the
 * result back to double.  Generated by macro to keep the source short.
 */

/* Local re-implementations matching wiring_natives.c — kept in sync. */
static int64_t hp_clamp_(int64_t x, int64_t lo, int64_t hi) {
    return x < lo ? lo : (x > hi ? hi : x);
}

/* Each wrapper casts double[]→int64[], computes, casts result→double. */
static double hp_add(int argc, const double *a) {
    (void)argc; return (double)((int64_t)a[0] + (int64_t)a[1]);
}
static double hp_subtract(int argc, const double *a) {
    (void)argc; return (double)((int64_t)a[0] - (int64_t)a[1]);
}
static double hp_multiply(int argc, const double *a) {
    (void)argc; return (double)((int64_t)a[0] * (int64_t)a[1]);
}
static double hp_divide(int argc, const double *a) {
    (void)argc;
    int64_t y = (int64_t)a[1];
    return (double)(y == 0 ? 0 : (int64_t)a[0] / y);
}
static double hp_negate(int argc, const double *a) {
    (void)argc; return (double)(-(int64_t)a[0]);
}
static double hp_abs_val(int argc, const double *a) {
    (void)argc; int64_t x = (int64_t)a[0]; return (double)(x < 0 ? -x : x);
}
static double hp_square(int argc, const double *a) {
    (void)argc; int64_t x = (int64_t)a[0]; return (double)(x * x);
}
static double hp_cube(int argc, const double *a) {
    (void)argc; int64_t x = (int64_t)a[0]; return (double)(x * x * x);
}
static double hp_double_val(int argc, const double *a) {
    (void)argc; return (double)((int64_t)a[0] * 2);
}
static double hp_triple_val(int argc, const double *a) {
    (void)argc; return (double)((int64_t)a[0] * 3);
}
static double hp_min_two(int argc, const double *a) {
    (void)argc; int64_t x = (int64_t)a[0], y = (int64_t)a[1];
    return (double)(x < y ? x : y);
}
static double hp_max_two(int argc, const double *a) {
    (void)argc; int64_t x = (int64_t)a[0], y = (int64_t)a[1];
    return (double)(x > y ? x : y);
}
static double hp_average_two(int argc, const double *a) {
    (void)argc; return (double)(((int64_t)a[0] + (int64_t)a[1]) / 2);
}
static double hp_distance_1d(int argc, const double *a) {
    (void)argc; int64_t d = (int64_t)a[0] - (int64_t)a[1];
    return (double)(d < 0 ? -d : d);
}
static double hp_midpoint(int argc, const double *a) {
    (void)argc; return (double)(((int64_t)a[0] + (int64_t)a[1]) / 2);
}
static double hp_mse(int argc, const double *a) {
    (void)argc; int64_t d = (int64_t)a[0] - (int64_t)a[1];
    return (double)(d * d);
}
static double hp_clamp(int argc, const double *a) {
    (void)argc; return (double)hp_clamp_((int64_t)a[0], (int64_t)a[1], (int64_t)a[2]);
}
static double hp_lerp(int argc, const double *a) {
    (void)argc; int64_t x = (int64_t)a[0], y = (int64_t)a[1], t = (int64_t)a[2];
    return (double)(x + ((y - x) * t) / 100);
}
static double hp_sigmoid(int argc, const double *a) {
    (void)argc; int64_t x = (int64_t)a[0];
    if (x <= -8) return 0;
    if (x >= 8)  return 100;
    static const int tbl[] = { 0,0,1,2,4,7,12,18,27,37,50,62,73,81,88,92,95,98,99,99,100 };
    int idx = (int)x + 10;
    if (idx < 0) idx = 0;
    if (idx > 20) idx = 20;
    return (double)tbl[idx];
}
static double hp_relu(int argc, const double *a) {
    (void)argc; int64_t x = (int64_t)a[0]; return (double)(x > 0 ? x : 0);
}
static double hp_tax_amount(int argc, const double *a) {
    (void)argc; return (double)(((int64_t)a[0] * (int64_t)a[1]) / 100);
}
static double hp_apply_tax(int argc, const double *a) {
    (void)argc; int64_t x = (int64_t)a[0], r = (int64_t)a[1];
    return (double)(x - (x * r) / 100);
}
static double hp_percentage(int argc, const double *a) {
    (void)argc; int64_t y = (int64_t)a[1];
    return (double)(y == 0 ? 0 : ((int64_t)a[0] * 100) / y);
}
static double hp_discount(int argc, const double *a) {
    (void)argc; int64_t p = (int64_t)a[0], r = (int64_t)a[1];
    return (double)(p - (p * r) / 100);
}
static double hp_markup(int argc, const double *a) {
    (void)argc; int64_t p = (int64_t)a[0], r = (int64_t)a[1];
    return (double)(p + (p * r) / 100);
}
static double hp_compound(int argc, const double *a) {
    (void)argc; int64_t p = (int64_t)a[0], rt = (int64_t)a[1], n = (int64_t)a[2];
    if (n < 0) n = 0; if (n > 30) n = 30;
    int64_t v = p;
    for (int64_t i = 0; i < n; i++) v = v + (v * rt) / 100;
    return (double)v;
}
static double hp_present_value(int argc, const double *a) {
    (void)argc; int64_t f = (int64_t)a[0], rt = (int64_t)a[1], n = (int64_t)a[2];
    if (n < 0) n = 0; if (n > 30) n = 30;
    int64_t v = f;
    for (int64_t i = 0; i < n; i++) v = (v * 100) / (100 + rt);
    return (double)v;
}
static double hp_future_value(int argc, const double *a) {
    return hp_compound(argc, a);
}
static double hp_factorial(int argc, const double *a) {
    (void)argc; int64_t n = (int64_t)a[0];
    if (n < 0) return 0;
    int64_t v = 1;
    for (int64_t i = 2; i <= n && i <= 20; i++) v *= i;
    return (double)v;
}
static double hp_fibonacci(int argc, const double *a) {
    (void)argc; int64_t n = (int64_t)a[0];
    if (n < 0) return 0;
    if (n < 2) return (double)n;
    int64_t prev = 0, cur = 1;
    for (int64_t i = 2; i <= n && i <= 90; i++) {
        int64_t nx = prev + cur; prev = cur; cur = nx;
    }
    return (double)cur;
}
static double hp_gcd(int argc, const double *a) {
    (void)argc;
    int64_t x = (int64_t)a[0]; if (x < 0) x = -x;
    int64_t y = (int64_t)a[1]; if (y < 0) y = -y;
    while (y) { int64_t t = y; y = x % y; x = t; }
    return (double)x;
}
static double hp_harmonic_n(int argc, const double *a) {
    (void)argc; int64_t n = (int64_t)a[0];
    if (n <= 0) return 0;
    int64_t s = 0;
    for (int64_t k = 1; k <= n && k <= 1000; k++) s += 1000 / k;
    return (double)s;
}
static double hp_circle_area(int argc, const double *a) {
    (void)argc; int64_t r = (int64_t)a[0];
    return (double)((314 * r * r) / 100);
}
static double hp_kinetic_energy(int argc, const double *a) {
    (void)argc; int64_t m = (int64_t)a[0], v = (int64_t)a[1];
    return (double)((m * v * v) / 2);
}
static double hp_bmi(int argc, const double *a) {
    (void)argc; int64_t w = (int64_t)a[0], h = (int64_t)a[1];
    return (double)(h == 0 ? 0 : (w * 10000) / (h * h));
}
static double hp_power(int argc, const double *a) {
    (void)argc; int64_t b = (int64_t)a[0], e = (int64_t)a[1];
    if (e < 0) return 0;
    int64_t v = 1;
    for (int64_t i = 0; i < e && i < 20; i++) v *= b;
    return (double)v;
}

static void register_all_natives(vm_engine *vm) {
    vm_engine_register_fn(vm, "add",            hp_add);
    vm_engine_register_fn(vm, "subtract",       hp_subtract);
    vm_engine_register_fn(vm, "multiply",       hp_multiply);
    vm_engine_register_fn(vm, "divide",         hp_divide);
    vm_engine_register_fn(vm, "negate",         hp_negate);
    vm_engine_register_fn(vm, "abs_val",        hp_abs_val);
    vm_engine_register_fn(vm, "square",         hp_square);
    vm_engine_register_fn(vm, "cube",           hp_cube);
    vm_engine_register_fn(vm, "double_val",     hp_double_val);
    vm_engine_register_fn(vm, "triple_val",     hp_triple_val);
    vm_engine_register_fn(vm, "min_two",        hp_min_two);
    vm_engine_register_fn(vm, "max_two",        hp_max_two);
    vm_engine_register_fn(vm, "average_two",    hp_average_two);
    vm_engine_register_fn(vm, "distance_1d",    hp_distance_1d);
    vm_engine_register_fn(vm, "midpoint",       hp_midpoint);
    vm_engine_register_fn(vm, "mse",            hp_mse);
    vm_engine_register_fn(vm, "clamp",          hp_clamp);
    vm_engine_register_fn(vm, "lerp",           hp_lerp);
    vm_engine_register_fn(vm, "sigmoid",        hp_sigmoid);
    vm_engine_register_fn(vm, "relu",           hp_relu);
    vm_engine_register_fn(vm, "tax_amount",     hp_tax_amount);
    vm_engine_register_fn(vm, "apply_tax",      hp_apply_tax);
    vm_engine_register_fn(vm, "percentage",     hp_percentage);
    vm_engine_register_fn(vm, "discount",       hp_discount);
    vm_engine_register_fn(vm, "markup",         hp_markup);
    vm_engine_register_fn(vm, "compound",       hp_compound);
    vm_engine_register_fn(vm, "present_value",  hp_present_value);
    vm_engine_register_fn(vm, "future_value",   hp_future_value);
    vm_engine_register_fn(vm, "factorial",      hp_factorial);
    vm_engine_register_fn(vm, "fibonacci",      hp_fibonacci);
    vm_engine_register_fn(vm, "gcd",            hp_gcd);
    vm_engine_register_fn(vm, "harmonic_n",     hp_harmonic_n);
    vm_engine_register_fn(vm, "circle_area",    hp_circle_area);
    vm_engine_register_fn(vm, "kinetic_energy", hp_kinetic_energy);
    vm_engine_register_fn(vm, "bmi",            hp_bmi);
    vm_engine_register_fn(vm, "power",          hp_power);
}

/* ============================================================
 *  Held-out file parsing.
 * ============================================================ */

#define MAX_HELD_OUT 64
#define MAX_PROMPT_LEN 512

typedef struct {
    char prompt[MAX_PROMPT_LEN];
    char expected[MAX_PROMPT_LEN];   /* comma-separated primitives */
    char reference[64];              /* reference function name */
    char input_order[MAX_PROMPT_LEN];/* comma-separated nouns matching reference S[0..N] (Phase 6b Stream E) */
} HeldOut;

static int load_held_out(const char *path, HeldOut *out, int max) {
    FILE *f = fopen(path, "r");
    if (!f) {
        fprintf(stderr, "harness: could not open %s\n", path);
        return -1;
    }
    char line[1024];
    int n = 0;
    HeldOut cur = {0};
    int have_prompt = 0;
    while (fgets(line, sizeof(line), f)) {
        /* Trim trailing newline. */
        size_t L = strlen(line);
        while (L && (line[L-1] == '\n' || line[L-1] == '\r' || line[L-1] == ' ')) {
            line[--L] = '\0';
        }
        if (L == 0) continue;

        if (line[0] == '/' && line[1] == '/') {
            const char *p = line + 2;
            while (*p == ' ') p++;
            strncpy(cur.prompt, p, sizeof(cur.prompt) - 1);
            cur.prompt[sizeof(cur.prompt) - 1] = '\0';
            have_prompt = 1;
        } else if (strncmp(line, "# EXPECTED:", 11) == 0) {
            const char *p = line + 11;
            while (*p == ' ') p++;
            strncpy(cur.expected, p, sizeof(cur.expected) - 1);
            cur.expected[sizeof(cur.expected) - 1] = '\0';
        } else if (strncmp(line, "# REFERENCE:", 12) == 0) {
            const char *p = line + 12;
            while (*p == ' ') p++;
            strncpy(cur.reference, p, sizeof(cur.reference) - 1);
            cur.reference[sizeof(cur.reference) - 1] = '\0';
        } else if (strncmp(line, "# INPUT_ORDER:", 14) == 0) {
            const char *p = line + 14;
            while (*p == ' ') p++;
            strncpy(cur.input_order, p, sizeof(cur.input_order) - 1);
            cur.input_order[sizeof(cur.input_order) - 1] = '\0';
        } else if (strcmp(line, "---") == 0) {
            if (have_prompt && n < max) {
                out[n++] = cur;
            }
            memset(&cur, 0, sizeof(cur));
            have_prompt = 0;
        }
        /* Skip other comment lines. */
    }
    fclose(f);
    return n;
}

/* ============================================================
 *  Scoring.
 * ============================================================ */

typedef struct {
    int verified;            /* graph parsed + verified */
    int correct;             /* matched reference on ≥3/5 input sets */
    int n_input_sets_match;  /* 0..5 */
    int n_nodes_used;
    int axis;                /* 1, 2, or 3 */
    const char *ref_name;
    char primitives[256];
} ResultRow;

int main(int argc, char **argv) {
    const char *path = (argc > 1) ? argv[1] : "pipeline_corpus_compositional_test.txt";

    HeldOut held[MAX_HELD_OUT];
    int n = load_held_out(path, held, MAX_HELD_OUT);
    if (n < 0) return 1;
    if (n == 0) {
        fprintf(stderr, "harness: no held-out prompts loaded from %s\n", path);
        return 1;
    }
    fprintf(stderr, "[Phase 5 harness] Loaded %d held-out prompts.\n", n);

    vm_engine *vm = vm_engine_create();
    register_all_natives(vm);

    ResultRow rows[MAX_HELD_OUT];
    memset(rows, 0, sizeof(rows));

    int axis_verified[4] = {0};   /* index 1..3 */
    int axis_correct[4]  = {0};
    int axis_total[4]    = {0};

    for (int i = 0; i < n; i++) {
        int axis = (i < 10) ? 1 : (i < 20) ? 2 : 3;
        rows[i].axis = axis;
        rows[i].ref_name = held[i].reference;
        axis_total[axis]++;

        WiringComposeReport report = {0};
        Pipeline *p = wiring_compositional_search(held[i].prompt, &report);

        if (!p) {
            printf("[%2d/30 axis%d] %-46s  NULL graph\n",
                   i + 1, axis, held[i].reference);
            continue;
        }
        rows[i].verified = report.verified;
        rows[i].n_nodes_used = report.n_nodes_used;
        if (report.verified) axis_verified[axis]++;

        /* Build a primitive list string. */
        size_t off = 0;
        for (int k = 0; k < report.n_nodes_used; k++) {
            const char *pn = report.primitive_names[k];
            if (!pn) continue;
            int w = snprintf(rows[i].primitives + off,
                             sizeof(rows[i].primitives) - off,
                             k == 0 ? "%s" : ",%s", pn);
            if (w < 0) break;
            off += (size_t)w;
            if (off >= sizeof(rows[i].primitives)) break;
        }

        /* Run on each of 5 input sets and score against reference.
         *
         * Stream E (Phase 6b): if a # INPUT_ORDER: noun list is annotated
         * for this prompt, we re-map the reference's positional S[0..N]
         * inputs onto the binder's noun-keyed signature inputs by name.
         * Without this, a topologically-correct graph whose sig inputs
         * were reordered by the binder scores against the wrong slots. */
        int matches = 0;

        /* Tokenise the INPUT_ORDER list into a small array of noun names. */
        char order_nouns[WIRING_MAX_INPUTS][32];
        int n_order_nouns = 0;
        if (held[i].input_order[0]) {
            const char *p = held[i].input_order;
            while (*p && n_order_nouns < WIRING_MAX_INPUTS) {
                while (*p == ' ' || *p == ',') p++;
                if (!*p) break;
                int len = 0;
                while (*p && *p != ',' && *p != ' ' && len < 31) {
                    char c = *p++;
                    if (c == '-') c = '_';
                    order_nouns[n_order_nouns][len++] = c;
                }
                order_nouns[n_order_nouns][len] = '\0';
                if (len > 0) n_order_nouns++;
            }
        }

        for (int s = 0; s < WIRING_INPUT_SETS; s++) {
            int64_t inputs_int[WIRING_MAX_INPUTS];
            wiring_input_set(s, inputs_int);

            PipelineValue inputs[WIRING_MAX_INPUTS] = {0};
            PipelineValue outputs[1] = {0};

            if (n_order_nouns > 0) {
                /* Noun-keyed mapping: inputs[k] in graph order ←
                 * inputs_int[j] where j is the index of report->signature_in_names[k]
                 * inside order_nouns[]. Falls back to positional if the
                 * graph noun is not in the order list. */
                for (int k = 0; k < report.signature_in_count && k < WIRING_MAX_INPUTS; k++) {
                    int j = -1;
                    const char *graph_noun = report.signature_in_names[k];
                    for (int q = 0; q < n_order_nouns; q++) {
                        if (strcmp(order_nouns[q], graph_noun) == 0) { j = q; break; }
                    }
                    inputs[k].v.i = (j >= 0) ? inputs_int[j] : inputs_int[k];
                }
            } else {
                for (int k = 0; k < report.signature_in_count && k < WIRING_MAX_INPUTS; k++) {
                    inputs[k].v.i = inputs_int[k];
                }
            }

            int rc = pipeline_execute_vm(p, vm, inputs, outputs);
            if (rc != PIPE_OK) continue;

            int64_t expected_v = 0;
            if (!wiring_reference_compute_at(held[i].reference, s, &expected_v))
                continue;
            if (outputs[0].v.i == expected_v) matches++;
        }
        rows[i].n_input_sets_match = matches;
        rows[i].correct = (matches >= 3) ? 1 : 0;
        if (rows[i].correct) axis_correct[axis]++;

        printf("[%2d/30 axis%d] %-30s  ver=%d nodes=%d match=%d/5  prims=[%s]%s\n",
               i + 1, axis, held[i].reference,
               report.verified, report.n_nodes_used,
               matches, rows[i].primitives,
               rows[i].correct ? "  CORRECT" : "");
    }

    int total_verified = axis_verified[1] + axis_verified[2] + axis_verified[3];
    int total_correct  = axis_correct[1]  + axis_correct[2]  + axis_correct[3];
    int total          = axis_total[1]    + axis_total[2]    + axis_total[3];

    printf("\n========================================================\n");
    printf("Phase 5 compositional held-out summary\n");
    printf("========================================================\n");
    for (int ax = 1; ax <= 3; ax++) {
        printf("  Axis %d (%-20s): verified %d/%-2d   correct %d/%-2d\n",
               ax,
               ax == 1 ? "novel pair"       :
               ax == 2 ? "synonym stress"   :
               ax == 3 ? "outer transform"  : "?",
               axis_verified[ax], axis_total[ax],
               axis_correct[ax],  axis_total[ax]);
    }
    printf("  ----------------------------------------\n");
    printf("  Total                  : verified %d/%d (%.0f%%)   correct %d/%d (%.0f%%)\n",
           total_verified, total,
           total ? (100.0 * total_verified / total) : 0.0,
           total_correct,  total,
           total ? (100.0 * total_correct  / total) : 0.0);
    printf("\nPre-registered targets (RESEARCH_DISCLOSURE.md §3.2):\n");
    printf("  default ranker             ≥ 50%% (15/30) verified-and-correct\n");
    printf("  with --use-expected gate    ≥ 80%% (24/30) verified-and-correct\n");

    vm_engine_dispose(vm);
    return 0;
}
