"""Export a snapped EML tree to a C99 header for the eml organelle.

Reads either:
  - a Mathematica `.m` file as produced by tree_prototype_torch_v16_final.py
    in the EML research repo (companion to microgpt-c), or
  - a PyTorch `.pt` state-dict snapshot of the EMLTree model.

Emits a C99 header file with:
  - static const unsigned char arrays for leaves, gates_left, gates_right
  - a static const EmlTree literal binding the arrays together
  - optional documentation block including the recovered symbolic form

This script is the deployment bridge: train in Python (see the eml research
repo's experiments/ dir), then run this tool to drop a snapped tree into a
microgpt-c demo as a compile-time constant.

Usage:
    python tools/eml_export.py --m runs/d2_all/d2_all_run01_seed137_biased_*.m \\
        --name eml_d2_recovered --out demos/character-level/eml_organelle/c_eml_tree.h
"""
import argparse
import re
import sys
from pathlib import Path
from typing import List, Tuple


def parse_m_file(path: Path) -> Tuple[int, List[List[int]], List[List[int]]]:
    """Parse a discretized .m file produced by the EML trainer.

    Looks for two assignments:
        leafWeights = {{0|1, 0|1, 0|1}, ...}
        blendSigmoid = {{0|1, 0|1}, ...}
    where each leafWeights row is a one-hot over (1, x, y) and each
    blendSigmoid row is a pair of 0|1 gates (left, right).

    Returns (depth, leaves_one_hot, gates_pairs) or raises ValueError.
    """
    text = path.read_text()

    # Skip the continuous (non-discretized) export if both blocks are present.
    if "Discretized: True" not in text and "Discretized: False" in text:
        # User passed the continuous variant; bail out clearly.
        raise ValueError(
            f"{path} is the continuous export ('Discretized: False'); "
            "pass the discretized .m (without _continuous suffix) instead."
        )

    leaf_match = re.search(r"leafWeights\s*=\s*\{(.+?)\};", text, re.DOTALL)
    gate_match = re.search(r"blendSigmoid\s*=\s*\{(.+?)\};", text, re.DOTALL)
    if not leaf_match or not gate_match:
        raise ValueError(f"{path}: missing leafWeights / blendSigmoid blocks")

    def parse_rows(blob: str) -> List[List[int]]:
        rows = re.findall(r"\{([^{}]+)\}", blob)
        out: List[List[int]] = []
        for r in rows:
            cells = [c.strip() for c in r.split(",")]
            try:
                ints = [int(c) for c in cells]
            except ValueError:
                # The float fallback path is for "uncertain" snaps; we don't
                # handle those here -- caller should re-train or hand-snap.
                raise ValueError(
                    f"{path}: non-integer cell in row '{r}'. Re-run trainer "
                    "until snap is clean (snap_threshold reached)."
                )
            out.append(ints)
        return out

    leaves = parse_rows(leaf_match.group(1))
    gates = parse_rows(gate_match.group(1))

    # leaves: one-hot over (1, x, y) — exactly one '1' per row
    for i, row in enumerate(leaves):
        if len(row) != 3 or sum(row) != 1 or any(v not in (0, 1) for v in row):
            raise ValueError(
                f"{path}: leaf row {i} = {row} not a one-hot triple")
    # gates: two 0/1 values per row (left, right)
    for i, row in enumerate(gates):
        if len(row) != 2 or any(v not in (0, 1) for v in row):
            raise ValueError(
                f"{path}: gate row {i} = {row} not a 0/1 pair")

    n_leaves = len(leaves)
    n_internal = len(gates)
    if n_leaves & (n_leaves - 1) != 0:
        raise ValueError(f"{path}: n_leaves={n_leaves} is not a power of 2")
    if n_internal != n_leaves - 1:
        raise ValueError(
            f"{path}: n_internal={n_internal} should be n_leaves-1={n_leaves-1}"
        )
    depth = n_leaves.bit_length() - 1
    return depth, leaves, gates


def leaves_to_choices(leaves: List[List[int]]) -> List[int]:
    """Convert one-hot rows over (1, x, y) to the 0/1/2 enum."""
    return [row.index(1) for row in leaves]


def emit_header(name: str, depth: int, leaf_choices: List[int],
                gates: List[List[int]], src: Path, target_desc: str = "") -> str:
    n_leaves = len(leaf_choices)
    n_internal = len(gates)
    gates_left = [g[0] for g in gates]
    gates_right = [g[1] for g in gates]

    def fmt(name: str, vals: List[int]) -> str:
        return ("static const unsigned char " + name +
                "[" + str(len(vals)) + "] = { " +
                ", ".join(str(v) for v in vals) + " };")

    header = f"""/*
 * Auto-generated by tools/eml_export.py from:
 *   {src}
 * DO NOT EDIT BY HAND. Re-run the export tool after re-training.
 *
 * Symbolic interpretation (informational): {target_desc or "(unspecified)"}
 *
 * Tree shape: depth={depth}, n_leaves={n_leaves}, n_internal={n_internal}.
 *   leaves[i]      ∈ {{0=1, 1=x, 2=y}}
 *   gates_left[i]  ∈ {{0=use child, 1=use constant 1}}
 *   gates_right[i] ∈ {{0=use child, 1=use constant 1}}
 */

#ifndef MICROGPT_EML_TREE_{name.upper()}_H
#define MICROGPT_EML_TREE_{name.upper()}_H

#include "microgpt_eml.h"

{fmt(name + "_leaves", leaf_choices)}
{fmt(name + "_gates_left", gates_left)}
{fmt(name + "_gates_right", gates_right)}

static const EmlTree {name} = {{
  .depth = {depth},
  .n_leaves = {n_leaves},
  .n_internal = {n_internal},
  .leaves = {name}_leaves,
  .gates_left = {name}_gates_left,
  .gates_right = {name}_gates_right,
}};

#endif /* MICROGPT_EML_TREE_{name.upper()}_H */
"""
    return header


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--m", type=Path, required=True,
                    help="Path to the discretized Mathematica .m file from the trainer")
    ap.add_argument("--name", type=str, required=True,
                    help="C identifier for the EmlTree literal (e.g. eml_d2_recovered)")
    ap.add_argument("--out", type=Path, required=True,
                    help="Output .h path")
    ap.add_argument("--target-desc", type=str, default="",
                    help="Free-text description embedded in the header comment")
    args = ap.parse_args()

    depth, leaves, gates = parse_m_file(args.m)
    leaf_choices = leaves_to_choices(leaves)
    header = emit_header(args.name, depth, leaf_choices, gates,
                         args.m, args.target_desc)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(header)
    print(f"Exported snapped tree (depth={depth}, "
          f"{len(leaf_choices)} leaves) to {args.out}")


if __name__ == "__main__":
    main()
